import {
  AcademicProgramme,
  CourseLevel,
  ExaminingBody,
  StudyMode,
  AcademicStructure,
} from '../types';

export interface ProgrammeFilterParams {
  query?: string;
  institutionId?: string;
  county?: string;
  level?: CourseLevel | 'All';
  award?: string;
  field?: string;
  examiningBody?: ExaminingBody | 'All';
  modeOfStudy?: StudyMode | 'All';
  regulator?: 'CUE' | 'TVETA' | 'All';
}

/**
 * MASTER KENYAN TERTIARY PROGRAMMES & COURSES CATALOGUE
 * Built from authoritative Commission for University Education (CUE) approved programmes
 * and Technical and Vocational Education and Training Authority (TVETA) course registers.
 */
export const COMPREHENSIVE_KENYAN_PROGRAMMES: AcademicProgramme[] = [
  // =========================================================================
  // 1. UNIVERSITY OF NAIROBI (UoN) - CUE CHARTERED PUBLIC UNIVERSITY
  // =========================================================================
  {
    id: 'uon-phd-cs',
    programmeId: 'uon-phd-cs',
    institutionId: 'uon',
    institutionName: 'University of Nairobi',
    code: 'P80',
    programmeCode: 'P80',
    name: 'Doctor of Philosophy (PhD) in Computer Science',
    programmeName: 'Doctor of Philosophy (PhD) in Computer Science',
    award: 'Doctorate',
    level: 'Doctorate (PhD)',
    qualificationLevel: 'Doctorate (PhD)',
    field: 'Computing & Information Technology',
    schoolId: 'uon-sci-tech',
    schoolName: 'Faculty of Science and Technology',
    department: 'Department of Computing and Informatics',
    campusId: 'uon-chiromo',
    campus: 'Chiromo Campus (Science & Tech)',
    duration: '3 - 5 Academic Years',
    durationYears: 3,
    durationTermsOrSemesters: 6,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Part-time', 'Blended Learning'],
    studyModes: ['Full-time', 'Part-time', 'Blended Learning'],
    entryRequirements: {
      minimumMeanGrade: 'Master of Science in Computer Science or equivalent from a CUE-recognized university',
      requiredClusterSubjects: ['Advanced Research Proposal Defense', 'Publications in Peer-Reviewed Journals'],
      alternativeRequirements: 'MSc in Software Engineering, Data Science, or Information Systems with distinction',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved & Accredited Doctoral Programme',
    cueAccreditationNumber: 'CUE/PROG/PUB/UON/DOC-002',
    source: 'Commission for University Education (CUE) Official Approved Programmes Register',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-01T08:00:00Z',
    overview: 'Premier research doctorate focusing on advanced artificial intelligence, distributed systems, cybersecurity, and computational intelligence in African contexts.',
    careerProspects: ['University Professor', 'Principal AI Researcher', 'Chief Technology Officer (CTO)', 'R&D Director'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'CSC801', title: 'Advanced Research Methodologies & Scientific Writing', credits: 4, isCore: true },
          { code: 'CSC802', title: 'Theoretical Foundations of Computation', credits: 4, isCore: true },
          { code: 'CSC803', title: 'Advanced Topics in Machine Learning & Neural Networks', credits: 4, isCore: false },
        ],
      },
      {
        stageNumber: 2,
        stageName: 'Year 1 / Semester 2',
        units: [
          { code: 'CSC804', title: 'Doctoral Seminar & Literature Survey Defense', credits: 4, isCore: true },
          { code: 'CSC805', title: 'Distributed Systems & Cloud Computing Architectures', credits: 4, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'uon-msc-cs',
    programmeId: 'uon-msc-cs',
    institutionId: 'uon',
    institutionName: 'University of Nairobi',
    code: 'P58',
    programmeCode: 'P58',
    name: 'Master of Science in Computer Science',
    programmeName: 'Master of Science in Computer Science',
    award: 'Master',
    level: 'Master Degree',
    qualificationLevel: 'Master Degree',
    field: 'Computing & Information Technology',
    schoolId: 'uon-sci-tech',
    schoolName: 'Faculty of Science and Technology',
    department: 'Department of Computing and Informatics',
    campusId: 'uon-chiromo',
    campus: 'Chiromo Campus (Science & Tech)',
    duration: '2 Academic Years (4 Semesters)',
    durationYears: 2,
    durationTermsOrSemesters: 4,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Evening', 'Weekend', 'Blended Learning'],
    studyModes: ['Full-time', 'Evening', 'Weekend', 'Blended Learning'],
    entryRequirements: {
      minimumMeanGrade: 'Upper Second Class Honours Bachelor degree in Computer Science, Software Engineering or related discipline',
      requiredClusterSubjects: ['Strong background in Data Structures, Algorithms, and Mathematics'],
      alternativeRequirements: 'Lower Second Class Honours with at least two years relevant industrial experience',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved & Accredited Master Programme',
    cueAccreditationNumber: 'CUE/PROG/PUB/UON/MAS-011',
    source: 'Commission for University Education (CUE) Official Approved Programmes Register',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-01T08:00:00Z',
    overview: 'Rigorous postgraduate training combining coursework and research thesis covering distributed systems, machine learning, and high performance computing.',
    careerProspects: ['Lead Software Architect', 'Data Scientist', 'IT Research Director', 'Senior Systems Engineer'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'CSC701', title: 'Advanced Computer Algorithms', credits: 3, isCore: true },
          { code: 'CSC702', title: 'Advanced Database Systems & Big Data', credits: 3, isCore: true },
          { code: 'CSC703', title: 'Computer Networks & Security Architectures', credits: 3, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'uon-bsc-cs',
    programmeId: 'uon-bsc-cs',
    institutionId: 'uon',
    institutionName: 'University of Nairobi',
    code: 'P15',
    programmeCode: 'P15',
    name: 'Bachelor of Science in Computer Science',
    programmeName: 'Bachelor of Science in Computer Science',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Computing & Information Technology',
    schoolId: 'uon-sci-tech',
    schoolName: 'Faculty of Science and Technology',
    department: 'Department of Computing and Informatics',
    campusId: 'uon-chiromo',
    campus: 'Chiromo Campus (Science & Tech)',
    duration: '4 Academic Years (8 Semesters)',
    durationYears: 4,
    durationTermsOrSemesters: 8,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Evening'],
    studyModes: ['Full-time', 'Evening'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C+ (Plus)',
      requiredClusterSubjects: ['Mathematics: B+', 'Physics: B', 'English/Kiswahili: C+'],
      alternativeRequirements: 'Accredited KNEC Diploma in Computer Studies or Information Technology with Credit pass',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved & Accredited Undergraduate Programme',
    cueAccreditationNumber: 'CUE/PROG/PUB/UON/014',
    source: 'Commission for University Education (CUE) Official Approved Programmes Register',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-01T08:00:00Z',
    overview: 'Flagship computing degree covering algorithms, software engineering, artificial intelligence, computer architecture, databases, and cybersecurity.',
    careerProspects: ['Software Engineer', 'Full-stack Developer', 'Cybersecurity Analyst', 'DevOps Engineer'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'CSC111', title: 'Introduction to Programming (C/C++)', credits: 3, isCore: true },
          { code: 'CSC112', title: 'Computer Architecture & Digital Logic', credits: 3, isCore: true },
          { code: 'SMA101', title: 'Calculus I for Computing Sciences', credits: 3, isCore: true },
          { code: 'SMA103', title: 'Discrete Mathematics', credits: 3, isCore: true },
          { code: 'CCS001', title: 'Communication Skills', credits: 2, isCore: true },
        ],
      },
      {
        stageNumber: 2,
        stageName: 'Year 1 / Semester 2',
        units: [
          { code: 'CSC121', title: 'Object-Oriented Programming (Java)', credits: 3, isCore: true },
          { code: 'CSC122', title: 'Data Structures and Algorithms', credits: 3, isCore: true },
          { code: 'SMA102', title: 'Calculus II for Computing Sciences', credits: 3, isCore: true },
          { code: 'CCS008', title: 'Critical and Creative Thinking', credits: 2, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'uon-bcom',
    programmeId: 'uon-bcom',
    institutionId: 'uon',
    institutionName: 'University of Nairobi',
    code: 'D33',
    programmeCode: 'D33',
    name: 'Bachelor of Commerce (B.Com)',
    programmeName: 'Bachelor of Commerce (B.Com)',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Business & Economics',
    schoolId: 'uon-business',
    schoolName: 'Faculty of Business and Management Sciences',
    department: 'Department of Business Administration',
    campusId: 'uon-kabete-lower',
    campus: 'Lower Kabete Campus (Business & Management)',
    duration: '4 Academic Years (8 Semesters)',
    durationYears: 4,
    durationTermsOrSemesters: 8,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Evening', 'Distance / Online', 'Blended Learning'],
    studyModes: ['Full-time', 'Evening', 'Distance / Online', 'Blended Learning'],
    specialization: 'Accounting, Finance, Marketing, Human Resource Management, Operations',
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C+ (Plus)',
      requiredClusterSubjects: ['Mathematics: C+', 'English or Kiswahili: C+'],
      alternativeRequirements: 'KASNEB CPA (Part II) or KNEC Diploma in Business Management with Credit pass',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved & Accredited Undergraduate Programme',
    cueAccreditationNumber: 'CUE/PROG/PUB/UON/028',
    source: 'Commission for University Education (CUE) Official Approved Programmes Register',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-01T08:00:00Z',
    overview: 'Comprehensive business degree providing rigorous foundation in accounting, financial markets, strategic management, corporate governance, and economic analytics.',
    careerProspects: ['Financial Analyst', 'Auditor', 'Investment Banker', 'Marketing Manager'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'DAC101', title: 'Principles of Financial Accounting I', credits: 3, isCore: true },
          { code: 'DBA101', title: 'Introduction to Business Studies', credits: 3, isCore: true },
          { code: 'DEC101', title: 'Microeconomics I', credits: 3, isCore: true },
          { code: 'DMS101', title: 'Business Mathematics', credits: 3, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'uon-llb',
    programmeId: 'uon-llb',
    institutionId: 'uon',
    institutionName: 'University of Nairobi',
    code: 'G34',
    programmeCode: 'G34',
    name: 'Bachelor of Laws (LL.B)',
    programmeName: 'Bachelor of Laws (LL.B)',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Law & Legal Studies',
    schoolId: 'uon-law',
    schoolName: 'Faculty of Law',
    department: 'Department of Public Law',
    campusId: 'uon-parklands',
    campus: 'Parklands Campus (School of Law)',
    duration: '4 Academic Years (8 Semesters)',
    durationYears: 4,
    durationTermsOrSemesters: 8,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Evening'],
    studyModes: ['Full-time', 'Evening'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade B (Plain)',
      requiredClusterSubjects: ['English: B', 'Kiswahili: B', 'Mathematics or History: B'],
      alternativeRequirements: 'Bachelor degree in another discipline from recognized university with upper second',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved & Council of Legal Education (CLE) Accredited',
    cueAccreditationNumber: 'CUE/PROG/PUB/UON/032',
    source: 'Commission for University Education (CUE) & Council of Legal Education (CLE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-01T08:00:00Z',
    overview: 'Preeminent legal education programme covering constitutional law, criminal law, contracts, property law, human rights, and jurisprudence.',
    careerProspects: ['Advocate of the High Court of Kenya', 'Corporate Legal Counsel', 'Judicial Officer', 'Legal Policy Advisor'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'GPR101', title: 'Legal Research and Writing', credits: 4, isCore: true },
          { code: 'GPR102', title: 'Constitutional Law I', credits: 4, isCore: true },
          { code: 'GPR103', title: 'Law of Contract I', credits: 4, isCore: true },
          { code: 'GPR104', title: 'Criminal Law I', credits: 4, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'uon-mbchb',
    programmeId: 'uon-mbchb',
    institutionId: 'uon',
    institutionName: 'University of Nairobi',
    code: 'H31',
    programmeCode: 'H31',
    name: 'Bachelor of Medicine and Bachelor of Surgery (MBChB)',
    programmeName: 'Bachelor of Medicine and Bachelor of Surgery (MBChB)',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Health & Medical Sciences',
    schoolId: 'uon-health-sci',
    schoolName: 'Faculty of Health Sciences',
    department: 'Department of Clinical Medicine',
    campusId: 'uon-kenyatta-nat',
    campus: 'Kenyatta National Hospital (KNH) Campus',
    duration: '6 Academic Years (12 Semesters / Trimesters)',
    durationYears: 6,
    durationTermsOrSemesters: 12,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade A or A-',
      requiredClusterSubjects: ['Biology: A', 'Chemistry: A', 'Mathematics or Physics: B+', 'English/Kiswahili: B+'],
      alternativeRequirements: 'Kenya Medical Practitioners and Dentists Council (KMPDC) strict statutory threshold',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE & Kenya Medical Practitioners and Dentists Council (KMPDC) Accredited',
    cueAccreditationNumber: 'CUE/PROG/PUB/UON/005',
    source: 'Commission for University Education (CUE) & KMPDC Official Register',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-01T08:00:00Z',
    overview: 'Kenya’s premier medical training curriculum based at Kenyatta National Hospital, producing licensed medical officers and surgeons.',
    careerProspects: ['Medical Doctor', 'Surgeon', 'Clinical Researcher', 'Hospital Superintendent'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'HMB101', title: 'Human Anatomy I (Gross Anatomy & Histology)', credits: 5, isCore: true },
          { code: 'HMB102', title: 'Medical Biochemistry I', credits: 4, isCore: true },
          { code: 'HMB103', title: 'Medical Physiology I', credits: 4, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'uon-bsc-civil',
    programmeId: 'uon-bsc-civil',
    institutionId: 'uon',
    institutionName: 'University of Nairobi',
    code: 'F16',
    programmeCode: 'F16',
    name: 'Bachelor of Science in Civil Engineering',
    programmeName: 'Bachelor of Science in Civil Engineering',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Engineering & Built Environment',
    schoolId: 'uon-engineering',
    schoolName: 'Faculty of Engineering',
    department: 'Civil and Construction Engineering',
    campusId: 'uon-main',
    campus: 'Main Campus (University Way)',
    duration: '5 Academic Years (10 Semesters)',
    durationYears: 5,
    durationTermsOrSemesters: 10,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade B+ (Plus)',
      requiredClusterSubjects: ['Mathematics: A-', 'Physics: A-', 'Chemistry: B+', 'English/Kiswahili: C+'],
      alternativeRequirements: 'Engineers Board of Kenya (EBK) accredited Higher Diploma in Civil Engineering',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE & Engineers Board of Kenya (EBK) Accredited',
    cueAccreditationNumber: 'CUE/PROG/PUB/UON/051',
    source: 'Commission for University Education (CUE) & Engineers Board of Kenya',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-01T08:00:00Z',
    overview: 'Professional engineering programme covering structural mechanics, geotechnical engineering, hydraulics, transportation, and construction management.',
    careerProspects: ['Civil Engineer', 'Structural Engineer', 'Project Manager', 'Water Resources Engineer'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'FCE111', title: 'Engineering Mathematics I', credits: 4, isCore: true },
          { code: 'FCE112', title: 'Engineering Mechanics (Statics)', credits: 3, isCore: true },
          { code: 'FCE113', title: 'Engineering Drawing I', credits: 3, isCore: true },
          { code: 'FCE114', title: 'Introduction to Civil Engineering Practice', credits: 2, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'uon-dip-cs',
    programmeId: 'uon-dip-cs',
    institutionId: 'uon',
    institutionName: 'University of Nairobi',
    code: 'P10',
    programmeCode: 'P10',
    name: 'Diploma in Computer Science',
    programmeName: 'Diploma in Computer Science',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Computing & Information Technology',
    schoolId: 'uon-sci-tech',
    schoolName: 'Faculty of Science and Technology',
    department: 'Department of Computing and Informatics',
    campusId: 'uon-chiromo',
    campus: 'Chiromo Campus (Science & Tech)',
    duration: '2 Academic Years (4 Semesters)',
    durationYears: 2,
    durationTermsOrSemesters: 4,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Evening'],
    studyModes: ['Full-time', 'Evening'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C (Plain)',
      requiredClusterSubjects: ['Mathematics: C', 'Physics or Physical Science: C'],
      alternativeRequirements: 'Certificate in IT from recognized institution with Distinction or Credit',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved University Diploma',
    cueAccreditationNumber: 'CUE/PROG/PUB/UON/DIP-004',
    source: 'Commission for University Education (CUE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-01T08:00:00Z',
    overview: 'Practical diploma bridging students into software development, web applications, and database administration with direct pathway to BSc Computer Science.',
    careerProspects: ['Junior Programmer', 'Web Designer', 'Database Assistant', 'IT Helpdesk Specialist'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'DCS101', title: 'Fundamentals of Computing & Operating Systems', credits: 3, isCore: true },
          { code: 'DCS102', title: 'Structured Programming Principles', credits: 3, isCore: true },
          { code: 'DCS103', title: 'Basic Mathematics for Computing', credits: 3, isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 2. KENYATTA UNIVERSITY (KU) - CUE CHARTERED PUBLIC UNIVERSITY
  // =========================================================================
  {
    id: 'ku-phd-education',
    programmeId: 'ku-phd-education',
    institutionId: 'ku',
    institutionName: 'Kenyatta University',
    code: 'E83',
    programmeCode: 'E83',
    name: 'Doctor of Philosophy (PhD) in Educational Management and Policy Studies',
    programmeName: 'Doctor of Philosophy (PhD) in Educational Management and Policy Studies',
    award: 'Doctorate',
    level: 'Doctorate (PhD)',
    qualificationLevel: 'Doctorate (PhD)',
    field: 'Education & Humanities',
    schoolId: 'ku-edu',
    schoolName: 'School of Education',
    department: 'Department of Educational Management',
    campusId: 'ku-main',
    campus: 'Main Campus (Thika Road)',
    duration: '3 Academic Years',
    durationYears: 3,
    durationTermsOrSemesters: 6,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Part-time', 'Blended Learning'],
    studyModes: ['Full-time', 'Part-time', 'Blended Learning'],
    entryRequirements: {
      minimumMeanGrade: 'Master of Education (M.Ed) in Educational Administration, Planning, or Policy from an accredited institution',
      requiredClusterSubjects: ['Doctoral Research Concept Paper Approved by Departmental Graduate Board'],
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved & Accredited Doctoral Programme',
    cueAccreditationNumber: 'CUE/PROG/PUB/KU/DOC-005',
    source: 'Commission for University Education (CUE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-02T10:00:00Z',
    overview: 'National flagship doctorate in education policy, institutional leadership, curriculum evaluation, and educational economics.',
    careerProspects: ['Chief Education Officer', 'University Dean', 'UNESCO Policy Consultant', 'Senior Education Planner'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'EMP801', title: 'Advanced Theories of Educational Administration', credits: 4, isCore: true },
          { code: 'EMP802', title: 'Educational Policy Analysis & Implementation', credits: 4, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'ku-bsc-soft-eng',
    programmeId: 'ku-bsc-soft-eng',
    institutionId: 'ku',
    institutionName: 'Kenyatta University',
    code: 'J17',
    programmeCode: 'J17',
    name: 'Bachelor of Science in Software Engineering',
    programmeName: 'Bachelor of Science in Software Engineering',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Computing & Information Technology',
    schoolId: 'ku-eng',
    schoolName: 'School of Engineering and Architecture',
    department: 'Department of Computing and Information Technology',
    campusId: 'ku-main',
    campus: 'Main Campus (Thika Road)',
    duration: '4 Academic Years (8 Semesters)',
    durationYears: 4,
    durationTermsOrSemesters: 8,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C+ (Plus)',
      requiredClusterSubjects: ['Mathematics: B', 'Physics: B', 'English/Kiswahili: C+'],
      alternativeRequirements: 'Diploma in Software Engineering or Computer Science with credit from recognized college',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved Undergraduate Programme',
    cueAccreditationNumber: 'CUE/PROG/PUB/KU/021',
    source: 'Commission for University Education (CUE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-02T10:00:00Z',
    overview: 'Rigorous engineering of software systems, agile methodologies, cloud architectures, quality assurance, and mobile systems development.',
    careerProspects: ['Software Architect', 'Mobile App Engineer (Android/iOS)', 'QA Automation Engineer', 'Cloud DevOps Lead'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'EET100', title: 'Electricity and Magnetism for Engineers', credits: 3, isCore: true },
          { code: 'CIT101', title: 'Structured Programming in C', credits: 3, isCore: true },
          { code: 'SMA101', title: 'Basic Mathematics for Engineers', credits: 3, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'ku-bed-arts',
    programmeId: 'ku-bed-arts',
    institutionId: 'ku',
    institutionName: 'Kenyatta University',
    code: 'E35',
    programmeCode: 'E35',
    name: 'Bachelor of Education (Arts)',
    programmeName: 'Bachelor of Education (Arts)',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Education & Humanities',
    schoolId: 'ku-edu',
    schoolName: 'School of Education',
    department: 'Department of Educational Foundations',
    campusId: 'ku-main',
    campus: 'Main Campus (Thika Road)',
    duration: '4 Academic Years (8 Semesters)',
    durationYears: 4,
    durationTermsOrSemesters: 8,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Distance / Online', 'Blended Learning'],
    studyModes: ['Full-time', 'Distance / Online', 'Blended Learning'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C+ (Plus)',
      requiredClusterSubjects: ['Two teaching subjects with at least C+ grade each'],
      alternativeRequirements: 'Teachers Service Commission (TSC) compliant Diploma in Education',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved & Teachers Service Commission (TSC) Recognized',
    cueAccreditationNumber: 'CUE/PROG/PUB/KU/001',
    source: 'Commission for University Education (CUE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-02T10:00:00Z',
    overview: 'Kenya’s renowned secondary teacher training program providing pedagogical mastery and teaching specialization in two disciplines.',
    careerProspects: ['High School Principal', 'Curriculum Developer (KICD)', 'Education Officer (MoE)', 'TSC Teacher'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'EFN101', title: 'Philosophy of Education', credits: 3, isCore: true },
          { code: 'EFN102', title: 'History of Education in Africa', credits: 3, isCore: true },
          { code: 'PSY101', title: 'Introduction to Educational Psychology', credits: 3, isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 3. STRATHMORE UNIVERSITY - CUE CHARTERED PRIVATE UNIVERSITY
  // =========================================================================
  {
    id: 'su-msc-it',
    programmeId: 'su-msc-it',
    institutionId: 'strathmore',
    institutionName: 'Strathmore University',
    code: 'MSIT',
    programmeCode: 'MSIT',
    name: 'Master of Science in Information Technology (MSc IT)',
    programmeName: 'Master of Science in Information Technology (MSc IT)',
    award: 'Master',
    level: 'Master Degree',
    qualificationLevel: 'Master Degree',
    field: 'Computing & Information Technology',
    schoolId: 'su-scit',
    schoolName: 'School of Computing and Engineering Sciences',
    department: 'Department of Computing and Technology',
    campusId: 'su-madaraka',
    campus: 'Madaraka Main Campus (Ole Sangale Road)',
    duration: '2 Academic Years (4 Semesters)',
    durationYears: 2,
    durationTermsOrSemesters: 4,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Evening', 'Weekend', 'Blended Learning'],
    studyModes: ['Evening', 'Weekend', 'Blended Learning'],
    entryRequirements: {
      minimumMeanGrade: 'First or Upper Second Class degree in Computing, IT, or Engineering',
      requiredClusterSubjects: ['Pass in Strathmore University Graduate Entrance Examination & Interview'],
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved & Accredited Master Programme',
    cueAccreditationNumber: 'CUE/PROG/PRI/SU/MAS-003',
    source: 'Commission for University Education (CUE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-03T11:00:00Z',
    overview: 'Executive IT master focusing on enterprise architecture, cybersecurity governance, data analytics, and technological innovation.',
    careerProspects: ['Chief Information Officer (CIO)', 'Enterprise Architect', 'Information Security Officer (CISO)'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'MIT8101', title: 'Enterprise Information Systems Architecture', credits: 3, isCore: true },
          { code: 'MIT8102', title: 'Information Security Governance & Compliance', credits: 3, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'su-bbit',
    programmeId: 'su-bbit',
    institutionId: 'strathmore',
    institutionName: 'Strathmore University',
    code: 'BBIT',
    programmeCode: 'BBIT',
    name: 'Bachelor of Business Information Technology (BBIT)',
    programmeName: 'Bachelor of Business Information Technology (BBIT)',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Computing & Information Technology',
    schoolId: 'su-scit',
    schoolName: 'School of Computing and Engineering Sciences',
    department: 'Department of Computing and Technology',
    campusId: 'su-madaraka',
    campus: 'Madaraka Main Campus (Ole Sangale Road)',
    duration: '4 Academic Years (8 Semesters)',
    durationYears: 4,
    durationTermsOrSemesters: 8,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Evening'],
    studyModes: ['Full-time', 'Evening'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade B- (Minus)',
      requiredClusterSubjects: ['Mathematics: C+', 'English: C+'],
      alternativeRequirements: 'IB Diploma: 28 points, or Diploma in IT with Distinction',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved Undergraduate Programme',
    cueAccreditationNumber: 'CUE/PROG/PRI/SU/008',
    source: 'Commission for University Education (CUE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-03T11:00:00Z',
    overview: 'Pioneering intersection of enterprise management, business analytics, financial tech (FinTech), and software engineering.',
    careerProspects: ['Business Analyst', 'FinTech Product Manager', 'IT Consultant', 'Solutions Architect'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'BIT1101', title: 'Introduction to Business Computing', credits: 3, isCore: true },
          { code: 'BIT1102', title: 'Programming Foundations in Python', credits: 3, isCore: true },
          { code: 'BAC1101', title: 'Financial Accounting for Managers', credits: 3, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'su-dip-it',
    programmeId: 'su-dip-it',
    institutionId: 'strathmore',
    institutionName: 'Strathmore University',
    code: 'DIT',
    programmeCode: 'DIT',
    name: 'Diploma in Business Information Technology (DBIT)',
    programmeName: 'Diploma in Business Information Technology (DBIT)',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Computing & Information Technology',
    schoolId: 'su-scit',
    schoolName: 'School of Computing and Engineering Sciences',
    department: 'Department of Computing and Technology',
    campusId: 'su-madaraka',
    campus: 'Madaraka Main Campus (Ole Sangale Road)',
    duration: '1.5 Years (4 Semesters / Terms)',
    durationYears: 2,
    durationTermsOrSemesters: 4,
    academicPeriod: 'Semester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Evening'],
    studyModes: ['Full-time', 'Evening'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C (Plain)',
      requiredClusterSubjects: ['Mathematics: C', 'English: C'],
      alternativeRequirements: 'Certificate in Computer Applications or Business Management',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved Diploma Programme',
    cueAccreditationNumber: 'CUE/PROG/PRI/SU/DIP-002',
    source: 'Commission for University Education (CUE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-03T11:00:00Z',
    overview: 'Accelerated practical diploma developing web applications, accounting systems, and computer network administration.',
    careerProspects: ['IT Support Technician', 'Web Application Assistant', 'Network Administrator'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Stage 1 / Semester 1',
        units: [
          { code: 'DBIT101', title: 'Computer Hardware and System Software', credits: 3, isCore: true },
          { code: 'DBIT102', title: 'Introduction to Web Design (HTML/CSS/JS)', credits: 3, isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 4. THIKA TECHNICAL TRAINING INSTITUTE (Kiambu) - TVETA REGISTERED TVET
  // =========================================================================
  {
    id: 'ttti-dict-knec',
    programmeId: 'ttti-dict-knec',
    institutionId: 'thika-tti',
    institutionName: 'Thika Technical Training Institute',
    code: 'DICT-6',
    programmeCode: 'DICT-6',
    name: 'Diploma in Information Communication Technology (DICT - KNEC)',
    programmeName: 'Diploma in Information Communication Technology (DICT - KNEC)',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Computing & Information Technology',
    schoolId: 'ttti-ict',
    schoolName: 'Department of Information Communication Technology (ICT)',
    department: 'Computing and Informatics',
    campusId: 'ttti-main',
    campus: 'Main Campus (General Kago Road, Thika)',
    duration: '3 Academic Years (9 Terms / 3 Modules)',
    durationYears: 3,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'KNEC',
    modeOfStudy: ['Full-time', 'Part-time', 'Evening'],
    studyModes: ['Full-time', 'Part-time', 'Evening'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C- (Minus)',
      requiredClusterSubjects: ['Mathematics or Physics: D+', 'English or Kiswahili: D+'],
      alternativeRequirements: 'Pass in Craft / Certificate in Information Technology (KNEC Level 5)',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Registered & Licensed Course • KNEC Examined',
    tvetaCourseCode: 'TVETA/CRS/ICT/0042',
    registrationNumber: 'TVETA/PUB/TVC/0012/2016',
    source: 'Technical and Vocational Education and Training Authority (TVETA) Course Catalogue',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-05T09:00:00Z',
    overview: 'Modular TVET diploma tested under the Kenya National Examinations Council (KNEC) curriculum covering programming, system analysis, hardware, and networking.',
    careerProspects: ['Network Support Officer', 'Database Administrator Assistant', 'Systems Maintenance Technician'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Module 1 / Term 1',
        units: [
          { code: 'DICT101', title: 'Introduction to ICT and Ethics', isCore: true },
          { code: 'DICT102', title: 'Computer Applications I (Office & Databases)', isCore: true },
          { code: 'DICT103', title: 'Structured Programming in Pascal/C', isCore: true },
          { code: 'DICT104', title: 'Computational Mathematics', isCore: true },
          { code: 'DICT105', title: 'Communication Skills & Life Skills', isCore: true },
        ],
      },
      {
        stageNumber: 2,
        stageName: 'Module 2 / Term 1',
        units: [
          { code: 'DICT201', title: 'Systems Analysis and Design', isCore: true },
          { code: 'DICT202', title: 'Object Oriented Programming (Visual Basic/C#)', isCore: true },
          { code: 'DICT203', title: 'Database Management Systems (SQL)', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'ttti-ict-cdacc',
    programmeId: 'ttti-ict-cdacc',
    institutionId: 'thika-tti',
    institutionName: 'Thika Technical Training Institute',
    code: 'CDACC-ICT-L6',
    programmeCode: 'CDACC-ICT-L6',
    name: 'Diploma in Information Communication Technology (CBET Level 6)',
    programmeName: 'Diploma in Information Communication Technology (CBET Level 6)',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Computing & Information Technology',
    schoolId: 'ttti-ict',
    schoolName: 'Department of Information Communication Technology (ICT)',
    department: 'Software Engineering & Networking',
    campusId: 'ttti-main',
    campus: 'Main Campus (General Kago Road, Thika)',
    duration: '3 Academic Years (Modular Competency-Based Education & Training)',
    durationYears: 3,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Modular CBET',
    examiningBody: 'TVET-CDACC',
    modeOfStudy: ['Full-time', 'Blended Learning'],
    studyModes: ['Full-time', 'Blended Learning'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C- (Minus) or relevant National Vocational Certificate (NVCET Level II)',
      requiredClusterSubjects: ['Competency verification in digital literacy and basic numeracy'],
      alternativeRequirements: 'Level 5 Certificate in ICT CBET with industry attachment endorsement',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVET-CDACC Accredited Competency-Based Curriculum',
    tvetaCourseCode: 'CDACC/ENG/ICT/06/001',
    source: 'TVET Curriculum Development, Assessment and Certification Council (TVET-CDACC)',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-05T09:00:00Z',
    overview: 'Next-generation CBET curriculum evaluated directly against industry occupational standards, emphasizing hands-on project portfolios and real industrial placement.',
    careerProspects: ['Certified CBET ICT Developer', 'Cloud Infrastructure Technician', 'Network Operations Specialist'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Level 6 - Basic Competencies',
        units: [
          { code: 'ICT601', title: 'Demonstrate Workplace Communication', isCore: true },
          { code: 'ICT602', title: 'Demonstrate Digital Literacy & Cybersecurity Hygiene', isCore: true },
          { code: 'ICT603', title: 'Apply Entrepreneurial Skills in Tech Ventures', isCore: true },
        ],
      },
      {
        stageNumber: 2,
        stageName: 'Level 6 - Core Competencies',
        units: [
          { code: 'ICT604', title: 'Develop Desktop & Mobile Software Applications', isCore: true },
          { code: 'ICT605', title: 'Implement Computer Network Infrastructure (CCNA Aligned)', isCore: true },
          { code: 'ICT606', title: 'Manage Relational and NoSQL Databases', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'ttti-cit-knec',
    programmeId: 'ttti-cit-knec',
    institutionId: 'thika-tti',
    institutionName: 'Thika Technical Training Institute',
    code: 'CIT-5',
    programmeCode: 'CIT-5',
    name: 'Certificate in Information Communication Technology (CICT - Level 5)',
    programmeName: 'Certificate in Information Communication Technology (CICT - Level 5)',
    award: 'Certificate',
    level: 'Certificate (Level 5)',
    qualificationLevel: 'Certificate (Level 5)',
    field: 'Computing & Information Technology',
    schoolId: 'ttti-ict',
    schoolName: 'Department of Information Communication Technology (ICT)',
    department: 'Computing and Informatics',
    campusId: 'ttti-main',
    campus: 'Main Campus (General Kago Road, Thika)',
    duration: '2 Academic Years (6 Terms / 2 Modules)',
    durationYears: 2,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'KNEC',
    modeOfStudy: ['Full-time', 'Evening'],
    studyModes: ['Full-time', 'Evening'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade D (Plain)',
      requiredClusterSubjects: ['Mathematics: D', 'English/Kiswahili: D'],
      alternativeRequirements: 'Artisan Certificate in Computer Applications (KNEC Level 4) or NVCET Level 1',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Registered Craft Certificate • KNEC Examined',
    tvetaCourseCode: 'TVETA/CRS/ICT/0078',
    source: 'Technical and Vocational Education and Training Authority (TVETA)',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-05T09:00:00Z',
    overview: 'Craft certificate equipping graduates with computer repair, hardware maintenance, software configuration, and administrative office support skills.',
    careerProspects: ['Computer Repair Technician', 'ICT Lab Assistant', 'Data Entry Clerk', 'Cyber Cafe Manager'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Module 1 / Term 1',
        units: [
          { code: 'CIT101', title: 'Introduction to Computers & Operating Systems', isCore: true },
          { code: 'CIT102', title: 'Computer Applications (Word, Excel, Access)', isCore: true },
          { code: 'CIT103', title: 'Basic Electronics & Computer Hardware Maintenance', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'ttti-artisan-elec',
    programmeId: 'ttti-artisan-elec',
    institutionId: 'thika-tti',
    institutionName: 'Thika Technical Training Institute',
    code: 'ART-EE-4',
    programmeCode: 'ART-EE-4',
    name: 'Artisan in Electrical Installation (Level 4)',
    programmeName: 'Artisan in Electrical Installation (Level 4)',
    award: 'Artisan',
    level: 'Artisan (Level 4)',
    qualificationLevel: 'Artisan (Level 4)',
    field: 'Engineering & Built Environment',
    schoolId: 'ttti-elec',
    schoolName: 'Department of Electrical & Electronic Engineering',
    department: 'Power Systems',
    campusId: 'ttti-main',
    campus: 'Main Campus (General Kago Road, Thika)',
    duration: '1 Academic Year (3 Terms)',
    durationYears: 1,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'KNEC',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCPE Certificate or KCSE Mean Grade D- (Minus) or E',
      requiredClusterSubjects: ['Basic arithmetic and English proficiency'],
      alternativeRequirements: 'Youth polytechnic trade test pass or prior learning certification',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Registered Artisan Level 4 • KNEC Examined',
    tvetaCourseCode: 'TVETA/CRS/ART/0019',
    source: 'Technical and Vocational Education and Training Authority (TVETA)',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-05T09:00:00Z',
    overview: 'Vocational trade craft training certified electrical wiremen for domestic installations, conduit piping, lighting circuits, and basic safety regulations.',
    careerProspects: ['Licensed Domestic Electrician (EPRA Wireman C)', 'Building Wiring Technician'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Term 1 / Stage 1',
        units: [
          { code: 'ART101', title: 'Electrical Workshop Practice & Safety', isCore: true },
          { code: 'ART102', title: 'Domestic Conduit Installation', isCore: true },
          { code: 'ART103', title: 'Basic Electrical Science', isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 5. KABETE NATIONAL POLYTECHNIC (Nairobi) - TVETA NATIONAL POLYTECHNIC
  // =========================================================================
  {
    id: 'kabete-hdip-ee',
    programmeId: 'kabete-hdip-ee',
    institutionId: 'kabete-np',
    institutionName: 'Kabete National Polytechnic',
    code: 'HDIP-EE-PWR',
    programmeCode: 'HDIP-EE-PWR',
    name: 'Higher Diploma in Electrical & Electronics Engineering (Power Option)',
    programmeName: 'Higher Diploma in Electrical & Electronics Engineering (Power Option)',
    award: 'Higher Diploma',
    level: 'Higher Diploma',
    qualificationLevel: 'Higher Diploma',
    field: 'Engineering & Built Environment',
    schoolId: 'knp-elec',
    schoolName: 'Department of Electrical & Electronics Engineering',
    department: 'Power Engineering and Renewable Energy',
    campusId: 'knp-main',
    campus: 'Main Campus (Waiyaki Way, Kabete)',
    duration: '2 Academic Years (6 Terms)',
    durationYears: 2,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'KNEC',
    modeOfStudy: ['Evening', 'Weekend', 'Part-time'],
    studyModes: ['Evening', 'Weekend', 'Part-time'],
    entryRequirements: {
      minimumMeanGrade: 'Diploma in Electrical Engineering (Power or Telecommunications Option) from KNEC or accredited polytechnic',
      requiredClusterSubjects: ['Pass in Advanced Engineering Mathematics and Power Systems'],
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Approved Higher Diploma • KNEC Examined',
    tvetaCourseCode: 'TVETA/CRS/ENG/0008',
    source: 'TVETA National Polytechnic Register & KNEC Directorate of TVET Examinations',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-04T08:30:00Z',
    overview: 'Advanced engineering diploma training senior electrical technologists in power grid synchronization, high-voltage substations, and industrial automation.',
    careerProspects: ['Chief Electrical Technologist (KPLC/KenGen)', 'Substation Engineer', 'Industrial Automation Specialist'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Term 1 / Stage 1',
        units: [
          { code: 'HDE101', title: 'High Voltage Transmission & Substation Technology', isCore: true },
          { code: 'HDE102', title: 'Power System Protection & Switchgear', isCore: true },
          { code: 'HDE103', title: 'Advanced Control Engineering & PLC Programming', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'kabete-dip-mechatronics',
    programmeId: 'kabete-dip-mechatronics',
    institutionId: 'kabete-np',
    institutionName: 'Kabete National Polytechnic',
    code: 'DMECH-L6',
    programmeCode: 'DMECH-L6',
    name: 'Diploma in Mechatronics Engineering (CBET Level 6)',
    programmeName: 'Diploma in Mechatronics Engineering (CBET Level 6)',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Engineering & Built Environment',
    schoolId: 'knp-mech',
    schoolName: 'Department of Mechanical & Automotive Engineering',
    department: 'Mechatronics & Robotics',
    campusId: 'knp-main',
    campus: 'Main Campus (Waiyaki Way, Kabete)',
    duration: '3 Academic Years (9 Terms / CBET Units)',
    durationYears: 3,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Modular CBET',
    examiningBody: 'TVET-CDACC',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C- (Minus)',
      requiredClusterSubjects: ['Mathematics: C-', 'Physics: C-', 'Chemistry: D+'],
      alternativeRequirements: 'Craft Certificate in Mechanical or Electrical Engineering (KNEC Level 5)',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Approved National Polytechnic CBET Curriculum',
    tvetaCourseCode: 'CDACC/ENG/MEC/06/004',
    source: 'TVETA National Polytechnic Register & TVET-CDACC',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-04T08:30:00Z',
    overview: 'Cutting-edge interdisciplinary training integrating robotics, programmable logic controllers (PLCs), pneumatics, hydraulics, and automated assembly line maintenance.',
    careerProspects: ['Robotics Maintenance Technologist', 'Automation System Integrator', 'Industrial PLC Programmer'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Term 1',
        units: [
          { code: 'MEC101', title: 'Electro-Pneumatics & Hydraulic Systems', isCore: true },
          { code: 'MEC102', title: 'Microcontroller Interfacing & C Programming', isCore: true },
          { code: 'MEC103', title: 'Computer Aided Design (SolidWorks / AutoCAD)', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'kabete-craft-automotive',
    programmeId: 'kabete-craft-automotive',
    institutionId: 'kabete-np',
    institutionName: 'Kabete National Polytechnic',
    code: 'CAM-5',
    programmeCode: 'CAM-5',
    name: 'Craft Certificate in Automotive Engineering (KNEC Level 5)',
    programmeName: 'Craft Certificate in Automotive Engineering (KNEC Level 5)',
    award: 'Certificate',
    level: 'Certificate (Level 5)',
    qualificationLevel: 'Certificate (Level 5)',
    field: 'Engineering & Built Environment',
    schoolId: 'knp-mech',
    schoolName: 'Department of Mechanical & Automotive Engineering',
    department: 'Automotive Engineering',
    campusId: 'knp-main',
    campus: 'Main Campus (Waiyaki Way, Kabete)',
    duration: '2 Academic Years (6 Terms / 2 Modules)',
    durationYears: 2,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'KNEC',
    modeOfStudy: ['Full-time', 'Part-time'],
    studyModes: ['Full-time', 'Part-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade D (Plain)',
      requiredClusterSubjects: ['Mathematics: D', 'Physics or Physical Science: D'],
      alternativeRequirements: 'Artisan in Motor Vehicle Mechanics (Level 4)',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Registered Craft Certificate • KNEC Examined',
    tvetaCourseCode: 'TVETA/CRS/AUT/0034',
    source: 'Technical and Vocational Education and Training Authority (TVETA)',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-04T08:30:00Z',
    overview: 'Practical automotive training on internal combustion engines, modern electronic fuel injection (EFI), OBD-II diagnostics, and chassis systems.',
    careerProspects: ['Certified Motor Vehicle Mechanic', 'EFI Diagnostic Specialist', 'Fleet Maintenance Technician'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Module 1 / Term 1',
        units: [
          { code: 'CAM101', title: 'Automotive Engine Technology I', isCore: true },
          { code: 'CAM102', title: 'Automotive Electrical Systems & Batteries', isCore: true },
          { code: 'CAM103', title: 'Automotive Workshop Technology & Tools', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'kabete-artisan-mvm',
    programmeId: 'kabete-artisan-mvm',
    institutionId: 'kabete-np',
    institutionName: 'Kabete National Polytechnic',
    code: 'ART-MVM-4',
    programmeCode: 'ART-MVM-4',
    name: 'Artisan in Motor Vehicle Mechanics (Level 4)',
    programmeName: 'Artisan in Motor Vehicle Mechanics (Level 4)',
    award: 'Artisan',
    level: 'Artisan (Level 4)',
    qualificationLevel: 'Artisan (Level 4)',
    field: 'Engineering & Built Environment',
    schoolId: 'knp-mech',
    schoolName: 'Department of Mechanical & Automotive Engineering',
    department: 'Automotive Engineering',
    campusId: 'knp-main',
    campus: 'Main Campus (Waiyaki Way, Kabete)',
    duration: '1 Academic Year (3 Terms)',
    durationYears: 1,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'KNEC',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCPE Certificate or KCSE Mean Grade D- or E',
      requiredClusterSubjects: ['Basic mechanical aptitude and trade commitment'],
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Registered Artisan Level 4 • KNEC Examined',
    tvetaCourseCode: 'TVETA/CRS/ART/0025',
    source: 'TVETA Register',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-04T08:30:00Z',
    overview: 'Foundational garage trade training covering engine servicing, brake repairs, transmission fluid changes, and wheel alignment.',
    careerProspects: ['Garage Apprentice Mechanic', 'Service Bay Attendant'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Term 1 / Stage 1',
        units: [
          { code: 'MVM101', title: 'Engine Service & Lubrication Systems', isCore: true },
          { code: 'MVM102', title: 'Chassis, Suspension & Brake Servicing', isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 6. KENYA MEDICAL TRAINING COLLEGE (KMTC Nairobi) - MANDATED HEALTH INSTITUTION
  // =========================================================================
  {
    id: 'kmtc-hdip-clin-med',
    programmeId: 'kmtc-hdip-clin-med',
    institutionId: 'kmtc-nairobi',
    institutionName: 'Kenya Medical Training College (KMTC)',
    code: 'HDCM-REP',
    programmeCode: 'HDCM-REP',
    name: 'Higher Diploma in Clinical Medicine (Reproductive Health)',
    programmeName: 'Higher Diploma in Clinical Medicine (Reproductive Health)',
    award: 'Higher Diploma',
    level: 'Higher Diploma',
    qualificationLevel: 'Higher Diploma',
    field: 'Health & Medical Sciences',
    schoolId: 'kmtc-clin',
    schoolName: 'Department of Clinical Medicine',
    department: 'Department of Clinical Medicine',
    campusId: 'kmtc-main',
    campus: 'Nairobi Main Campus (KMTC Headquarters, Old Mbagathi Road)',
    duration: '1 Academic Year (2 Semesters)',
    durationYears: 1,
    durationTermsOrSemesters: 2,
    academicPeriod: 'Semester',
    examiningBody: 'Other',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'Diploma in Clinical Medicine and Surgery from KMTC or CUE/TVETA recognized college',
      requiredClusterSubjects: ['Current registration and valid practice license with Clinical Officers Council (COC)', 'At least two years post-internship clinical experience'],
    },
    tvetaAccredited: true,
    accreditationStatus: 'Mandated by KMTC Act & Clinical Officers Council (COC) Kenya',
    source: 'Kenya Medical Training College (KMTC) Academic Directorate & COC Kenya',
    sourceUrl: 'https://kmtc.ac.ke',
    lastVerifiedAt: '2026-09-02T14:00:00Z',
    overview: 'Specialized postgraduate diploma training registered clinical officers to manage complex obstetric emergencies, cesarean sections, gynecological surgeries, and reproductive health facilities.',
    careerProspects: ['Reproductive Health Specialist Clinical Officer', 'County Maternity Ward In-Charge'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Semester 1',
        units: [
          { code: 'RHM101', title: 'Advanced Emergency Obstetric and Neonatal Care (CEmONC)', isCore: true },
          { code: 'RHM102', title: 'Operative Obstetrics & Surgical Skills', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'kmtc-dip-clin-med',
    programmeId: 'kmtc-dip-clin-med',
    institutionId: 'kmtc-nairobi',
    institutionName: 'Kenya Medical Training College (KMTC)',
    code: 'DCM-L6',
    programmeCode: 'DCM-L6',
    name: 'Diploma in Clinical Medicine and Surgery',
    programmeName: 'Diploma in Clinical Medicine and Surgery',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Health & Medical Sciences',
    schoolId: 'kmtc-clin',
    schoolName: 'Department of Clinical Medicine',
    department: 'Department of Clinical Medicine',
    campusId: 'kmtc-main',
    campus: 'Nairobi Main Campus (KMTC Headquarters, Old Mbagathi Road)',
    duration: '3 Academic Years (6 Semesters / Trimesters)',
    durationYears: 3,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Semester',
    examiningBody: 'Other',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C (Plain)',
      requiredClusterSubjects: ['Biology: C', 'English or Kiswahili: C', 'Chemistry: C-', 'Mathematics or Physics: C-'],
    },
    tvetaAccredited: true,
    accreditationStatus: 'Mandated by KMTC Act & Clinical Officers Council (COC) Kenya',
    source: 'Kenya Medical Training College Official Course Catalogue',
    sourceUrl: 'https://kmtc.ac.ke',
    lastVerifiedAt: '2026-09-02T14:00:00Z',
    overview: 'Core clinical curriculum producing Kenya’s primary frontline healthcare clinicians authorized to examine patients, diagnose, prescribe treatment, and perform minor surgeries.',
    careerProspects: ['Registered Clinical Officer', 'Sub-County Hospital Clinical Lead', 'Health Center Manager'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'DCM101', title: 'Anatomy and Physiology I', isCore: true },
          { code: 'DCM102', title: 'Clinical Pharmacology I', isCore: true },
          { code: 'DCM103', title: 'Pathology & Microbiology', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'kmtc-dip-nursing',
    programmeId: 'kmtc-dip-nursing',
    institutionId: 'kmtc-nairobi',
    institutionName: 'Kenya Medical Training College (KMTC)',
    code: 'KRCHN',
    programmeCode: 'KRCHN',
    name: 'Kenya Registered Community Health Nursing (KRCHN Diploma)',
    programmeName: 'Kenya Registered Community Health Nursing (KRCHN Diploma)',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Health & Medical Sciences',
    schoolId: 'kmtc-nurs',
    schoolName: 'Department of Nursing',
    department: 'Department of Nursing',
    campusId: 'kmtc-main',
    campus: 'Nairobi Main Campus (KMTC Headquarters, Old Mbagathi Road)',
    duration: '3.5 Academic Years (7 Semesters)',
    durationYears: 3,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Semester',
    examiningBody: 'Other',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C (Plain)',
      requiredClusterSubjects: ['Biology: C', 'English or Kiswahili: C', 'Chemistry or Physics or Mathematics: C-'],
      alternativeRequirements: 'Nursing Council of Kenya (NCK) mandatory entry requirements',
    },
    tvetaAccredited: true,
    accreditationStatus: 'Nursing Council of Kenya (NCK) Accredited Diploma',
    source: 'Nursing Council of Kenya & KMTC Academic Registry',
    sourceUrl: 'https://kmtc.ac.ke',
    lastVerifiedAt: '2026-09-02T14:00:00Z',
    overview: 'Comprehensive nursing curriculum certifying nurses to deliver general bedside nursing, community midwifery, and pediatric preventive health programs.',
    careerProspects: ['Registered Nurse (NCK Licensed)', 'Community Health Nurse', 'Ward Sister / Charge Nurse'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'NRG101', title: 'Foundations of Nursing Practice & Ethics', isCore: true },
          { code: 'NRG102', title: 'Medical-Surgical Nursing I', isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 7. KENYA UTALII COLLEGE (Nairobi) - STATUTORY HOSPITALITY & TOURISM INSTITUTE
  // =========================================================================
  {
    id: 'utalii-dip-hm',
    programmeId: 'utalii-dip-hm',
    institutionId: 'kenya-utalii',
    institutionName: 'Kenya Utalii College',
    code: 'DHM-L6',
    programmeCode: 'DHM-L6',
    name: 'Diploma in Hotel Management',
    programmeName: 'Diploma in Hotel Management',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Hospitality & Tourism',
    schoolId: 'kuc-hotel',
    schoolName: 'Department of Hotel Management',
    department: 'Front Office and Food Service Operations',
    campusId: 'kuc-main',
    campus: 'Main Campus (Thika Road, Ruaraka)',
    duration: '3 Academic Years (Including 6 Months Hotel Internship)',
    durationYears: 3,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Semester',
    examiningBody: 'Other',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C (Plain)',
      requiredClusterSubjects: ['English or Kiswahili: C+', 'Mathematics: C-'],
      alternativeRequirements: 'Utalii Certificate in Food and Beverage or Front Office with credit',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA & Tourism Act 2011 Mandated Hospitality Qualification',
    source: 'Kenya Utalii College Academic Directorate & Tourism Regulatory Authority',
    sourceUrl: 'https://utalii.ac.ke',
    lastVerifiedAt: '2026-09-03T16:00:00Z',
    overview: 'World-renowned hospitality diploma training executive general managers, banquet leaders, revenue specialists, and international resort operators.',
    careerProspects: ['Hotel General Manager', 'Food & Beverage Director', 'Front Office Executive', 'Banqueting Manager'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'HM101', title: 'Front Office Management & Guest Experience', isCore: true },
          { code: 'HM102', title: 'Food & Beverage Service Principles', isCore: true },
          { code: 'HM103', title: 'Hospitality Accounting & Cost Control', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'utalii-craft-food-prod',
    programmeId: 'utalii-craft-food-prod',
    institutionId: 'kenya-utalii',
    institutionName: 'Kenya Utalii College',
    code: 'CFP-5',
    programmeCode: 'CFP-5',
    name: 'Craft Certificate in Food Production (Culinary Arts Level 5)',
    programmeName: 'Craft Certificate in Food Production (Culinary Arts Level 5)',
    award: 'Certificate',
    level: 'Certificate (Level 5)',
    qualificationLevel: 'Certificate (Level 5)',
    field: 'Hospitality & Tourism',
    schoolId: 'kuc-hotel',
    schoolName: 'Department of Hotel Management',
    department: 'Culinary Arts & Kitchen Operations',
    campusId: 'kuc-main',
    campus: 'Main Campus (Thika Road, Ruaraka)',
    duration: '2 Academic Years (4 Semesters)',
    durationYears: 2,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Semester',
    examiningBody: 'Other',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade D+ (Plus)',
      requiredClusterSubjects: ['English or Kiswahili: D+', 'Home Science or Biology: D+'],
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA & Tourism Regulatory Authority Approved Culinary Certificate',
    source: 'Kenya Utalii College',
    sourceUrl: 'https://utalii.ac.ke',
    lastVerifiedAt: '2026-09-03T16:00:00Z',
    overview: 'Hands-on chef training in hot kitchen production, cold larder, butchery, international gastronomy, food hygiene, and pastry arts.',
    careerProspects: ['Chef de Partie', 'Sous Chef', 'Pastry Chef', 'Catering Entrepreneur'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'CFP101', title: 'Culinary Fundamentals & Knife Skills', isCore: true },
          { code: 'CFP102', title: 'Food Safety, Hygiene & HACCP Standards', isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 8. KENYA INSTITUTE OF MASS COMMUNICATION (KIMC South B)
  // =========================================================================
  {
    id: 'kimc-dip-journalism',
    programmeId: 'kimc-dip-journalism',
    institutionId: 'kimc-nairobi',
    institutionName: 'Kenya Institute of Mass Communication (KIMC)',
    code: 'DJOURN-L6',
    programmeCode: 'DJOURN-L6',
    name: 'Diploma in Journalism and Media Studies',
    programmeName: 'Diploma in Journalism and Media Studies',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Media & Communication',
    schoolId: 'kimc-jour',
    schoolName: 'Department of Journalism & Media Studies',
    department: 'Print and Broadcast Journalism',
    campusId: 'kimc-main',
    campus: 'Main Campus (South B, Uholo Road)',
    duration: '3 Academic Years (6 Semesters)',
    durationYears: 3,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Semester',
    examiningBody: 'KNEC',
    modeOfStudy: ['Full-time', 'Evening'],
    studyModes: ['Full-time', 'Evening'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C (Plain)',
      requiredClusterSubjects: ['English: C+', 'Kiswahili: C+'],
      alternativeRequirements: 'Media Council of Kenya (MCK) accredited certificate with distinction',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Registered & Media Council of Kenya (MCK) Recognized',
    tvetaCourseCode: 'TVETA/CRS/MED/0015',
    source: 'TVETA Register & Media Council of Kenya (MCK)',
    sourceUrl: 'https://kimc.ac.ke',
    lastVerifiedAt: '2026-09-04T12:00:00Z',
    overview: 'Flagship broadcasting journalism academy producing television news anchors, investigative reporters, podcasters, radio producers, and digital editors.',
    careerProspects: ['Television News Anchor / Reporter', 'Radio News Editor', 'Digital Media Producer', 'Public Relations Specialist'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Year 1 / Semester 1',
        units: [
          { code: 'JRN101', title: 'News Writing and Reporting for Print & Broadcast', isCore: true },
          { code: 'JRN102', title: 'Media Law, Ethics and Constitutional Freedoms', isCore: true },
          { code: 'JRN103', title: 'Radio Production & Sound Engineering', isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 9. KANGEMI VOCATIONAL TRAINING CENTRE (Nairobi) - VTC / NITA LEVEL
  // =========================================================================
  {
    id: 'kangemi-nita-electrical',
    programmeId: 'kangemi-nita-electrical',
    institutionId: 'kangemi-vtc',
    institutionName: 'Kangemi Vocational Training Centre',
    code: 'NITA-ELEC-G3',
    programmeCode: 'NITA-ELEC-G3',
    name: 'National Trade Test in Electrical Wireman (Grade III / II / I)',
    programmeName: 'National Trade Test in Electrical Wireman (Grade III / II / I)',
    award: 'Vocational',
    level: 'Grade III / Vocational',
    qualificationLevel: 'Grade III / Vocational',
    field: 'Engineering & Built Environment',
    schoolId: 'kvtc-elec',
    schoolName: 'Electrical Installation Trade Department',
    department: 'Electrical Installation Workshop',
    campusId: 'kvtc-main',
    campus: 'Main Centre (Kangemi Central, Westlands Sub-County)',
    duration: '1 Year (Practical Apprenticeship)',
    durationYears: 1,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'NITA',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'Open Access: Primary School KCPE or KCSE certificate or youth polytechnic attendee',
      requiredClusterSubjects: ['Willingness to undertake manual and technical hands-on training'],
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Licensed Vocational Training Centre • NITA Examined',
    tvetaCourseCode: 'TVETA/VTC/NITA/002',
    source: 'National Industrial Training Authority (NITA) & TVETA County Registry',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-04T15:00:00Z',
    overview: 'Practical trade certification accredited by NITA preparing licensed electricians for residential buildings, conduit laying, fault rectification, and single-phase wiring.',
    careerProspects: ['Certified EPRA Class C Wireman', 'Site Electrical Contractor'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Term 1 / Hands-on Stage',
        units: [
          { code: 'NTE101', title: 'Workshop Safety & Hand Tool Operations', isCore: true },
          { code: 'NTE102', title: 'Surface & Concealed Conduit Wiring', isCore: true },
          { code: 'NTE103', title: 'Earth Leakage Protection & Circuit Testing', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'kangemi-artisan-fb',
    programmeId: 'kangemi-artisan-fb',
    institutionId: 'kangemi-vtc',
    institutionName: 'Kangemi Vocational Training Centre',
    code: 'ART-FB-4',
    programmeCode: 'ART-FB-4',
    name: 'Artisan in Food and Beverage Service & Production (Level 4)',
    programmeName: 'Artisan in Food and Beverage Service & Production (Level 4)',
    award: 'Artisan',
    level: 'Artisan (Level 4)',
    qualificationLevel: 'Artisan (Level 4)',
    field: 'Hospitality & Tourism',
    schoolId: 'kvtc-hosp',
    schoolName: 'Hospitality & Catering Trade Department',
    department: 'Food and Beverage Section',
    campusId: 'kvtc-main',
    campus: 'Main Centre (Kangemi Central, Westlands Sub-County)',
    duration: '1 Year (3 Terms)',
    durationYears: 1,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'KNEC',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCPE or KCSE certificate',
      requiredClusterSubjects: ['Basic hospitality aptitude'],
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Registered Artisan Qualification • KNEC Examined',
    tvetaCourseCode: 'TVETA/CRS/VTC/0088',
    source: 'TVETA County Register',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-04T15:00:00Z',
    overview: 'Foundational culinary trade training for catering enterprises, canteen operations, local bakeries, and dining hall management.',
    careerProspects: ['Catering Assistant', 'Restaurant Waiter/Waitress', 'Bakery Assistant'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Term 1',
        units: [
          { code: 'VFB101', title: 'Basic Baking and Pastry Principles', isCore: true },
          { code: 'VFB102', title: 'Table Setting and Guest Care', isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 10. PC KINYANJUI TECHNICAL TRAINING INSTITUTE (Nairobi)
  // =========================================================================
  {
    id: 'pck-dict-knec',
    programmeId: 'pck-dict-knec',
    institutionId: 'pc-kinyanjui-tti',
    institutionName: 'PC Kinyanjui Technical Training Institute',
    code: 'PCK-DICT-6',
    programmeCode: 'PCK-DICT-6',
    name: 'Diploma in Information Communication Technology (KNEC Level 6)',
    programmeName: 'Diploma in Information Communication Technology (KNEC Level 6)',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Computing & Information Technology',
    schoolId: 'pck-ict',
    schoolName: 'Department of Information Communication Technology',
    department: 'Computing and Systems Support',
    campusId: 'pck-main',
    campus: 'Main Campus (Kabiria Road, Riruta Satellite)',
    duration: '3 Academic Years (9 Terms / 3 Modules)',
    durationYears: 3,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'KNEC',
    modeOfStudy: ['Full-time', 'Evening'],
    studyModes: ['Full-time', 'Evening'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C- (Minus)',
      requiredClusterSubjects: ['Mathematics: D+', 'English/Kiswahili: D+'],
      alternativeRequirements: 'Certificate in ICT (Level 5) with pass',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Registered & Licensed • KNEC Examined',
    tvetaCourseCode: 'TVETA/CRS/ICT/0055',
    source: 'TVETA Course Catalogue',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-04T10:00:00Z',
    overview: 'Modular vocational diploma covering computer networking, Linux systems administration, web development, and quantitative techniques.',
    careerProspects: ['Systems Support Analyst', 'Network Administrator Assistant', 'ICT Trainer'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Module 1 / Term 1',
        units: [
          { code: 'PCK101', title: 'Computer Hardware & System Software', isCore: true },
          { code: 'PCK102', title: 'Programming Fundamentals in C', isCore: true },
        ],
      },
    ],
  },
  {
    id: 'pck-dip-building',
    programmeId: 'pck-dip-building',
    institutionId: 'pc-kinyanjui-tti',
    institutionName: 'PC Kinyanjui Technical Training Institute',
    code: 'DBT-6',
    programmeCode: 'DBT-6',
    name: 'Diploma in Building and Civil Technology',
    programmeName: 'Diploma in Building and Civil Technology',
    award: 'Diploma',
    level: 'Diploma (Level 6)',
    qualificationLevel: 'Diploma (Level 6)',
    field: 'Engineering & Built Environment',
    schoolId: 'pck-civil',
    schoolName: 'Department of Building and Civil Engineering',
    department: 'Building Construction Technology',
    campusId: 'pck-main',
    campus: 'Main Campus (Kabiria Road, Riruta Satellite)',
    duration: '3 Academic Years (9 Terms / 3 Modules)',
    durationYears: 3,
    durationTermsOrSemesters: 3,
    academicPeriod: 'Term',
    examiningBody: 'KNEC',
    modeOfStudy: ['Full-time'],
    studyModes: ['Full-time'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C- (Minus)',
      requiredClusterSubjects: ['Mathematics: C-', 'Physics: C-'],
      alternativeRequirements: 'Craft in Masonry or Plumbing with credit pass',
    },
    tvetaAccredited: true,
    accreditationStatus: 'TVETA Registered • KNEC Examined',
    tvetaCourseCode: 'TVETA/CRS/BLD/0014',
    source: 'TVETA Register',
    sourceUrl: 'https://tveta.go.ke',
    lastVerifiedAt: '2026-09-04T10:00:00Z',
    overview: 'Comprehensive construction technology diploma covering surveying, structural masonry, concrete technology, and quantity estimation.',
    careerProspects: ['Building Site Supervisor', 'Clerk of Works', 'Assistant Quantity Surveyor'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Module 1 / Term 1',
        units: [
          { code: 'DBT101', title: 'Building Construction Technology I', isCore: true },
          { code: 'DBT102', title: 'Land Surveying I & Leveling', isCore: true },
        ],
      },
    ],
  },

  // =========================================================================
  // 11. KENYA METHODIST UNIVERSITY (KeMU) - CUE CHARTERED PRIVATE UNIVERSITY
  // =========================================================================
  {
    id: 'kemu-bsc-cis',
    programmeId: 'kemu-bsc-cis',
    institutionId: 'kemu',
    institutionName: 'Kenya Methodist University',
    code: 'CIS-101',
    programmeCode: 'CIS-101',
    name: 'Bachelor of Science in Computer Information Systems (CIS)',
    programmeName: 'Bachelor of Science in Computer Information Systems (CIS)',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Computing & Information Technology',
    schoolId: 'kemu-sci-tech',
    schoolName: 'School of Science and Technology',
    department: 'Department of Computer Science and Business IT',
    campusId: 'kemu-nairobi-hub',
    campus: 'Nairobi Campus (KEMU Hub, Koinange Street)',
    duration: '4 Academic Years (8 Semesters / Trimesters)',
    durationYears: 4,
    durationTermsOrSemesters: 8,
    academicPeriod: 'Trimester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Evening', 'Weekend', 'Distance / Online'],
    studyModes: ['Full-time', 'Evening', 'Weekend', 'Distance / Online'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C+ (Plus)',
      requiredClusterSubjects: ['Mathematics: C+', 'English: C+'],
      alternativeRequirements: 'Diploma in CIS or IT from KeMU or accredited institution with distinction',
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved & Accredited Programme',
    cueAccreditationNumber: 'CUE/PROG/PRI/KMU/011',
    source: 'Commission for University Education (CUE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-04T14:00:00Z',
    overview: 'Applied computing curriculum connecting database architectures, information systems management, cloud solutions, and software development.',
    careerProspects: ['Systems Analyst', 'Database Administrator', 'Enterprise IT Consultant'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Trimester 1',
        units: [
          { code: 'CIS110', title: 'Introduction to Computer Systems', credits: 3, isCore: true },
          { code: 'CIS111', title: 'Structured Programming Using C++', credits: 3, isCore: true },
        ],
      },
    ],
  },
  {
    id: 'kemu-bba',
    programmeId: 'kemu-bba',
    institutionId: 'kemu',
    institutionName: 'Kenya Methodist University',
    code: 'BBA-201',
    programmeCode: 'BBA-201',
    name: 'Bachelor of Business Administration (BBA)',
    programmeName: 'Bachelor of Business Administration (BBA)',
    award: 'Bachelor',
    level: 'Bachelor Degree',
    qualificationLevel: 'Bachelor Degree',
    field: 'Business & Economics',
    schoolId: 'kemu-business',
    schoolName: 'School of Business and Economics',
    department: 'Department of Business Administration',
    campusId: 'kemu-nairobi-hub',
    campus: 'Nairobi Campus (KEMU Hub, Koinange Street)',
    duration: '4 Academic Years (8 Trimesters)',
    durationYears: 4,
    durationTermsOrSemesters: 8,
    academicPeriod: 'Trimester',
    examiningBody: 'University Senate',
    modeOfStudy: ['Full-time', 'Evening', 'Weekend', 'Distance / Online'],
    studyModes: ['Full-time', 'Evening', 'Weekend', 'Distance / Online'],
    entryRequirements: {
      minimumMeanGrade: 'KCSE Mean Grade C+ (Plus)',
      requiredClusterSubjects: ['Mathematics: C', 'English/Kiswahili: C+'],
    },
    cueAccredited: true,
    accreditationStatus: 'CUE Approved Programme',
    cueAccreditationNumber: 'CUE/PROG/PRI/KMU/005',
    source: 'Commission for University Education (CUE)',
    sourceUrl: 'https://www.cue.or.ke',
    lastVerifiedAt: '2026-09-04T14:00:00Z',
    overview: 'Flexible business degree with specializations in Finance, Accounting, Marketing, and Human Resource Management.',
    careerProspects: ['Business Executive', 'Accountant', 'HR Officer', 'Procurement Officer'],
    curriculumStages: [
      {
        stageNumber: 1,
        stageName: 'Trimester 1',
        units: [
          { code: 'BBA101', title: 'Principles of Management', credits: 3, isCore: true },
          { code: 'ACT101', title: 'Financial Accounting Principles', credits: 3, isCore: true },
        ],
      },
    ],
  },
];

// Helper: retrieve all programmes
export function getAllCataloguedProgrammes(): AcademicProgramme[] {
  return COMPREHENSIVE_KENYAN_PROGRAMMES;
}

// Helper: search programmes across the country with multi-dimensional criteria
export function searchComprehensiveProgrammes(filters?: ProgrammeFilterParams): AcademicProgramme[] {
  let list = [...COMPREHENSIVE_KENYAN_PROGRAMMES];
  if (!filters) return list;

  if (filters.query && filters.query.trim()) {
    const q = filters.query.toLowerCase().trim();
    list = list.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.code.toLowerCase().includes(q) ||
        (p.programmeName && p.programmeName.toLowerCase().includes(q)) ||
        (p.field && p.field.toLowerCase().includes(q)) ||
        (p.specialization && p.specialization.toLowerCase().includes(q)) ||
        (p.institutionName && p.institutionName.toLowerCase().includes(q)) ||
        p.department.toLowerCase().includes(q)
    );
  }

  if (filters.institutionId && filters.institutionId !== 'All') {
    const instId = filters.institutionId.toLowerCase();
    list = list.filter((p) => p.institutionId.toLowerCase() === instId);
  }

  if (filters.level && filters.level !== 'All') {
    list = list.filter((p) => p.level === filters.level || p.qualificationLevel === filters.level);
  }

  if (filters.award && filters.award !== 'All') {
    list = list.filter((p) => p.award.toLowerCase() === filters.award!.toLowerCase());
  }

  if (filters.field && filters.field !== 'All') {
    list = list.filter((p) => p.field === filters.field);
  }

  if (filters.examiningBody && filters.examiningBody !== 'All') {
    list = list.filter((p) => p.examiningBody === filters.examiningBody);
  }

  if (filters.modeOfStudy && filters.modeOfStudy !== 'All') {
    list = list.filter((p) => {
      if (Array.isArray(p.modeOfStudy)) {
        return p.modeOfStudy.includes(filters.modeOfStudy as StudyMode);
      }
      return p.modeOfStudy === filters.modeOfStudy;
    });
  }

  if (filters.regulator && filters.regulator !== 'All') {
    list = list.filter((p) => {
      if (filters.regulator === 'CUE') {
        return p.cueAccredited || p.source?.includes('CUE');
      }
      if (filters.regulator === 'TVETA') {
        return p.tvetaAccredited || p.source?.includes('TVETA');
      }
      return true;
    });
  }

  return list;
}

// Helper: Get distinct disciplines/fields
export function getAllDistinctFields(): string[] {
  const fields = new Set<string>();
  COMPREHENSIVE_KENYAN_PROGRAMMES.forEach((p) => {
    if (p.field) fields.add(p.field);
  });
  return Array.from(fields).sort();
}

// Helper: Get distinct qualification levels
export function getAllDistinctLevels(): CourseLevel[] {
  return [
    'Doctorate (PhD)',
    'Master Degree',
    'Postgraduate Diploma',
    'Bachelor Degree',
    'Higher Diploma',
    'Diploma (Level 6)',
    'Certificate (Level 5)',
    'Artisan (Level 4)',
    'Grade III / Vocational',
  ];
}

// Helper: Get distinct examining bodies
export function getAllDistinctExaminingBodies(): ExaminingBody[] {
  return ['University Senate', 'KNEC', 'TVET-CDACC', 'NITA', 'KASNEB', 'KIM', 'Other'];
}
