import {
  Institution,
  CampusFacility,
  CampusStudentService,
  CampusEvent,
  ProgrammeUnit,
} from '../types';

// =========================================================================
// OFFICIAL TVETA & CUE ALL-KENYA TERTIARY EDUCATION REGISTER
// (Universities, University Colleges, TVET Colleges, National Polytechnics,
//  Vocational Training Centres, and Accredited Professional Institutes)
// =========================================================================

export const TVETA_VERIFIED_INSTITUTIONS: Institution[] = [
  // 1. THIKA TECHNICAL TRAINING INSTITUTE (Kiambu)
  {
    id: 'thika-tti',
    name: 'Thika Technical Training Institute',
    shortName: 'TTTI',
    type: 'TVET / Technical College',
    ownership: 'Public',
    regulator: 'TVETA',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'TVETA/PUB/TVC/0012/2016',
    accreditation: 'Registered and Licensed by TVET Authority (TVETA) Kenya • Mandated Qualification Awarding Body',
    source: 'Technical and Vocational Education and Training Authority (TVETA) Official Register & TTTI Academic Registry',
    lastVerifiedAt: '2026-09-05T09:00:00Z',
    logo: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-amber-400 bg-amber-500/10 text-amber-300',
    website: 'https://thikatechnical.ac.ke',
    county: 'Kiambu',
    generalContacts: {
      phone: '+254 67 222 1952',
      email: 'info@thikatechnical.ac.ke',
      emergency: '+254 722 000 012',
      postalAddress: 'P.O. Box 91 - 01000, General Kago Road, Thika, Kenya',
    },
    campuses: [
      {
        id: 'ttti-main',
        institutionId: 'thika-tti',
        name: 'Main Campus (General Kago Road, Thika)',
        county: 'Kiambu',
        town: 'Thika Town',
        address: 'General Kago Road, opposite Thika Level 5 Hospital, Thika',
        coordinates: { lat: -1.0378, lng: 37.0765 },
        contacts: {
          phone: '+254 67 222 1952',
          email: 'principal@thikatechnical.ac.ke',
          emergency: '+254 722 456 789',
        },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'ttti-ict',
        institutionId: 'thika-tti',
        name: 'Department of Information Communication Technology (ICT)',
        code: 'ICT-DEPT',
        departments: ['Computing and Informatics', 'Software Engineering & Networking', 'Digital Media'],
      },
      {
        id: 'ttti-elec',
        institutionId: 'thika-tti',
        name: 'Department of Electrical & Electronic Engineering',
        code: 'EEE-DEPT',
        departments: ['Power Systems', 'Telecommunications', 'Instrumentation & Control'],
      },
      {
        id: 'ttti-mech',
        institutionId: 'thika-tti',
        name: 'Department of Mechanical & Automotive Engineering',
        code: 'MAE-DEPT',
        departments: ['Automotive Technology', 'Production Engineering', 'Plant Engineering'],
      },
      {
        id: 'ttti-business',
        institutionId: 'thika-tti',
        name: 'Department of Business & Entrepreneurship Studies',
        code: 'BES-DEPT',
        departments: ['Supply Chain & Logistics', 'Accounting & Finance', 'Business Management'],
      },
      {
        id: 'ttti-hospitality',
        institutionId: 'thika-tti',
        name: 'Department of Hospitality & Institutional Management',
        code: 'HIM-DEPT',
        departments: ['Food and Beverage Production', 'Catering & Accommodation'],
      },
    ],
    programmes: [
      {
        id: 'ttti-dict-knec',
        institutionId: 'thika-tti',
        code: 'DICT-6',
        name: 'Diploma in Information Communication Technology (DICT)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'ttti-ict',
        department: 'Computing and Informatics',
        durationYears: 3,
        durationTermsOrSemesters: 3,
        tvetaAccredited: true,
        tvetaCourseCode: 'TVETA/CRS/ICT/0042',
      },
      {
        id: 'ttti-ict-cdacc',
        institutionId: 'thika-tti',
        code: 'CDACC-ICT-L6',
        name: 'Diploma in Information Communication Technology (CBET)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'TVET-CDACC',
        schoolId: 'ttti-ict',
        department: 'Software Engineering & Networking',
        durationYears: 3,
        durationTermsOrSemesters: 3,
        tvetaAccredited: true,
        tvetaCourseCode: 'CDACC/ENG/ICT/06/001',
      },
      {
        id: 'ttti-cit-knec',
        institutionId: 'thika-tti',
        code: 'CIT-5',
        name: 'Certificate in Information Communication Technology (CICT)',
        award: 'Certificate',
        level: 'Certificate (Level 5)',
        examiningBody: 'KNEC',
        schoolId: 'ttti-ict',
        department: 'Computing and Informatics',
        durationYears: 2,
        durationTermsOrSemesters: 3,
        tvetaAccredited: true,
      },
      {
        id: 'ttti-ee-power',
        institutionId: 'thika-tti',
        code: 'DEEE-PWR',
        name: 'Diploma in Electrical Engineering (Power Option)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'ttti-elec',
        department: 'Power Systems',
        durationYears: 3,
        durationTermsOrSemesters: 3,
        tvetaAccredited: true,
      },
      {
        id: 'ttti-auto-knec',
        institutionId: 'thika-tti',
        code: 'DAE-6',
        name: 'Diploma in Automotive Engineering',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'TVET-CDACC',
        schoolId: 'ttti-mech',
        department: 'Automotive Technology',
        durationYears: 3,
        durationTermsOrSemesters: 3,
        tvetaAccredited: true,
      },
      {
        id: 'ttti-artisan-plumbing',
        institutionId: 'thika-tti',
        code: 'ART-PLUMB',
        name: 'Artisan Certificate in Plumbing & Pipe Fitting',
        award: 'Artisan',
        level: 'Artisan (Level 4)',
        examiningBody: 'KNEC',
        schoolId: 'ttti-mech',
        department: 'Production Engineering',
        durationYears: 1,
        durationTermsOrSemesters: 3,
        tvetaAccredited: true,
      },
    ],
  },

  // 2. THE KABETE NATIONAL POLYTECHNIC (Nairobi)
  {
    id: 'kabete-poly',
    name: 'The Kabete National Polytechnic',
    shortName: 'Kabete NP',
    type: 'National Polytechnic',
    ownership: 'Public',
    regulator: 'TVETA',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'TVETA/PUB/NP/0001/2017',
    accreditation: 'Upgraded to National Polytechnic Status under TVET Act • TVETA Registered and Licensed',
    source: 'TVET Authority Kenya Register & Kabete National Polytechnic Academic Directorate',
    lastVerifiedAt: '2026-09-05T10:00:00Z',
    logo: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-emerald-400 bg-emerald-500/10 text-emerald-300',
    website: 'https://kabetepoly.ac.ke',
    county: 'Nairobi',
    generalContacts: {
      phone: '+254 20 205 9931',
      email: 'info@kabetepoly.ac.ke',
      emergency: '+254 722 000 002',
      postalAddress: 'P.O. Box 29010 - 00625, Kangemi, Nairobi, Kenya',
    },
    campuses: [
      {
        id: 'kabete-main',
        institutionId: 'kabete-poly',
        name: 'Main Campus (Waiyaki Way, Kabete)',
        county: 'Nairobi',
        town: 'Kabete / Kangemi',
        address: 'Waiyaki Way, Near Kabete Approved School, Nairobi',
        coordinates: { lat: -1.2592, lng: 36.7215 },
        contacts: {
          phone: '+254 20 205 9931',
          email: 'principal@kabetepoly.ac.ke',
          emergency: '+254 722 999 111',
        },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'kabete-cs',
        institutionId: 'kabete-poly',
        name: 'Department of Computer Studies & Informatics',
        code: 'DCS',
        departments: ['Software Development', 'Cybersecurity', 'Network Systems'],
      },
      {
        id: 'kabete-mechatronics',
        institutionId: 'kabete-poly',
        name: 'Department of Mechatronics & Mechanical Engineering',
        code: 'DME',
        departments: ['Mechatronics & Automation', 'Mechanical Production', 'Industrial Plant'],
      },
      {
        id: 'kabete-electrical',
        institutionId: 'kabete-poly',
        name: 'Department of Electrical & Electronics Engineering',
        code: 'DEE',
        departments: ['Power & Energy', 'Telecommunications & Microelectronics'],
      },
    ],
    programmes: [
      {
        id: 'kabete-dict',
        institutionId: 'kabete-poly',
        code: 'KNP-DICT-6',
        name: 'Diploma in Information Communication Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'TVET-CDACC',
        schoolId: 'kabete-cs',
        department: 'Software Development',
        durationYears: 3,
        tvetaAccredited: true,
      },
      {
        id: 'kabete-mecha-l6',
        institutionId: 'kabete-poly',
        code: 'KNP-MECHA-6',
        name: 'Diploma in Mechatronics Engineering Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'TVET-CDACC',
        schoolId: 'kabete-mechatronics',
        department: 'Mechatronics & Automation',
        durationYears: 3,
        tvetaAccredited: true,
      },
      {
        id: 'kabete-elec-power',
        institutionId: 'kabete-poly',
        code: 'KNP-EEE-6',
        name: 'Diploma in Electrical Engineering (Power Option)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'kabete-electrical',
        department: 'Power & Energy',
        durationYears: 3,
        tvetaAccredited: true,
      },
    ],
  },

  // 3. KISUMU NATIONAL POLYTECHNIC (Kisumu)
  {
    id: 'kisumu-poly',
    name: 'The Kisumu National Polytechnic',
    shortName: 'Kisumu NP',
    type: 'National Polytechnic',
    ownership: 'Public',
    regulator: 'TVETA',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'TVETA/PUB/NP/0003/2017',
    accreditation: 'Premier National Polytechnic in Western Region • Licensed by TVETA Kenya',
    source: 'TVETA Official Register & Kisumu National Polytechnic Registrar Office',
    lastVerifiedAt: '2026-09-05T11:00:00Z',
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-cyan-400 bg-cyan-500/10 text-cyan-300',
    website: 'https://kisumupoly.ac.ke',
    county: 'Kisumu',
    generalContacts: {
      phone: '+254 57 202 2071',
      email: 'info@kisumupoly.ac.ke',
      emergency: '+254 722 000 003',
      postalAddress: 'P.O. Box 143 - 40100, Technology Road, Kisumu, Kenya',
    },
    campuses: [
      {
        id: 'kisumu-poly-main',
        institutionId: 'kisumu-poly',
        name: 'Main Campus (Technology Road, Kisumu)',
        county: 'Kisumu',
        town: 'Kisumu City',
        address: 'Technology Road, off Nairobi-Kisumu Highway, Kisumu',
        coordinates: { lat: -0.1022, lng: 34.7617 },
        contacts: {
          phone: '+254 57 202 2071',
          email: 'principal@kisumupoly.ac.ke',
        },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'knp-computing',
        institutionId: 'kisumu-poly',
        name: 'Department of Computing and Informatics',
        code: 'DCI',
        departments: ['Computer Science & IT', 'Cybersecurity & Networks'],
      },
      {
        id: 'knp-civil',
        institutionId: 'kisumu-poly',
        name: 'Department of Building and Civil Engineering',
        code: 'DBCE',
        departments: ['Civil Works & Highways', 'Architecture & Structural Draftsmanship'],
      },
      {
        id: 'knp-health',
        institutionId: 'kisumu-poly',
        name: 'Department of Health & Applied Sciences',
        code: 'DHAS',
        departments: ['Medical Laboratory Science', 'Analytical Chemistry'],
      },
    ],
    programmes: [
      {
        id: 'knp-dict',
        institutionId: 'kisumu-poly',
        code: 'KNP-IT-6',
        name: 'Diploma in Information Communication Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'TVET-CDACC',
        schoolId: 'knp-computing',
        department: 'Computer Science & IT',
        durationYears: 3,
        tvetaAccredited: true,
      },
      {
        id: 'knp-civil-diploma',
        institutionId: 'kisumu-poly',
        code: 'KNP-CIVIL-6',
        name: 'Diploma in Civil Engineering (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'knp-civil',
        department: 'Civil Works & Highways',
        durationYears: 3,
        tvetaAccredited: true,
      },
      {
        id: 'knp-medlab',
        institutionId: 'kisumu-poly',
        code: 'KNP-MLS-6',
        name: 'Diploma in Medical Laboratory Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'knp-health',
        department: 'Medical Laboratory Science',
        durationYears: 3,
        tvetaAccredited: true,
      },
    ],
  },

  // 4. KENYA COAST NATIONAL POLYTECHNIC (Mombasa)
  {
    id: 'kenya-coast-poly',
    name: 'Kenya Coast National Polytechnic',
    shortName: 'KCNP',
    type: 'National Polytechnic',
    ownership: 'Public',
    regulator: 'TVETA',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'TVETA/PUB/NP/0002/2017',
    accreditation: 'Centre of Excellence in Marine and Transport Logistics • TVETA Licensed',
    source: 'TVET Authority Kenya & Kenya Coast National Polytechnic Secretariat',
    lastVerifiedAt: '2026-09-05T12:00:00Z',
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-blue-400 bg-blue-500/10 text-blue-300',
    website: 'https://kenyacoastpoly.ac.ke',
    county: 'Mombasa',
    generalContacts: {
      phone: '+254 41 249 2222',
      email: 'info@kenyacoastpoly.ac.ke',
      emergency: '+254 722 000 004',
      postalAddress: 'P.O. Box 81220 - 80100, Kisauni Road, Mombasa, Kenya',
    },
    campuses: [
      {
        id: 'kcnp-main',
        institutionId: 'kenya-coast-poly',
        name: 'Main Campus (Kisauni Road, Mombasa)',
        county: 'Mombasa',
        town: 'Mombasa Island',
        address: 'Kisauni Road, Bondeni, Mombasa',
        coordinates: { lat: -4.0532, lng: 39.6738 },
        contacts: { phone: '+254 41 249 2222', email: 'principal@kenyacoastpoly.ac.ke' },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'kcnp-ict',
        institutionId: 'kenya-coast-poly',
        name: 'Department of Computing & Information Science',
        code: 'DCIS',
        departments: ['Computing Systems', 'Digital Logistics Technology'],
      },
      {
        id: 'kcnp-marine',
        institutionId: 'kenya-coast-poly',
        name: 'School of Marine Engineering & Blue Economy',
        code: 'SMEBE',
        departments: ['Marine Engineering', 'Maritime Transport & Port Logistics'],
      },
    ],
    programmes: [
      {
        id: 'kcnp-marine-diploma',
        institutionId: 'kenya-coast-poly',
        code: 'KCNP-MAR-6',
        name: 'Diploma in Maritime Transport and Logistics (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'TVET-CDACC',
        schoolId: 'kcnp-marine',
        department: 'Maritime Transport & Port Logistics',
        durationYears: 3,
        tvetaAccredited: true,
      },
      {
        id: 'kcnp-dict',
        institutionId: 'kenya-coast-poly',
        code: 'KCNP-DICT-6',
        name: 'Diploma in Information Communication Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'kcnp-ict',
        department: 'Computing Systems',
        durationYears: 3,
        tvetaAccredited: true,
      },
    ],
  },

  // 5. RIFT VALLEY TECHNICAL TRAINING INSTITUTE (RVTTI - Eldoret)
  {
    id: 'rvtti',
    name: 'Rift Valley Technical Training Institute',
    shortName: 'RVTTI',
    type: 'TVET / Technical College',
    ownership: 'Public',
    regulator: 'TVETA',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'TVETA/PUB/TVC/0008/2016',
    accreditation: 'UNESCO-UNEVOC Centre of Excellence in Technical Training • TVETA Licensed',
    source: 'TVET Authority Official Registry & RVTTI Academic Office',
    lastVerifiedAt: '2026-09-05T13:00:00Z',
    logo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-teal-400 bg-teal-500/10 text-teal-300',
    website: 'https://rvtti.ac.ke',
    county: 'Uasin Gishu',
    generalContacts: {
      phone: '+254 53 206 0303',
      email: 'info@rvtti.ac.ke',
      emergency: '+254 722 000 005',
      postalAddress: 'P.O. Box 244 - 30100, Eldoret, Kenya',
    },
    campuses: [
      {
        id: 'rvtti-main',
        institutionId: 'rvtti',
        name: 'Main Campus (Eldoret Town)',
        county: 'Uasin Gishu',
        town: 'Eldoret',
        address: 'Kisumu-Eldoret Highway, Eldoret',
        coordinates: { lat: 0.5143, lng: 35.2698 },
        contacts: { phone: '+254 53 206 0303', email: 'principal@rvtti.ac.ke' },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'rvtti-cs',
        institutionId: 'rvtti',
        name: 'Department of Computer Studies',
        code: 'DCS',
        departments: ['Information Technology', 'Software Engineering'],
      },
      {
        id: 'rvtti-electrical',
        institutionId: 'rvtti',
        name: 'Department of Electrical & Renewable Energy',
        code: 'DERE',
        departments: ['Solar Energy Systems', 'Electrical Power'],
      },
    ],
    programmes: [
      {
        id: 'rvtti-dict',
        institutionId: 'rvtti',
        code: 'RV-DICT-6',
        name: 'Diploma in Information Communication Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'TVET-CDACC',
        schoolId: 'rvtti-cs',
        department: 'Information Technology',
        durationYears: 3,
        tvetaAccredited: true,
      },
      {
        id: 'rvtti-solar-diploma',
        institutionId: 'rvtti',
        code: 'RV-SOLAR-6',
        name: 'Diploma in Electrical & Renewable Energy Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'rvtti-electrical',
        department: 'Solar Energy Systems',
        durationYears: 3,
        tvetaAccredited: true,
      },
    ],
  },

  // 6. NAIROBI TECHNICAL TRAINING INSTITUTE (NTTI - Nairobi)
  {
    id: 'ntti',
    name: 'Nairobi Technical Training Institute',
    shortName: 'NTTI',
    type: 'TVET / Technical College',
    ownership: 'Public',
    regulator: 'TVETA',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'TVETA/PUB/TVC/0005/2016',
    accreditation: 'Registered and Licensed by TVETA Kenya • Government Technical Training College',
    source: 'TVET Authority Official Register & NTTI Academic Registry',
    lastVerifiedAt: '2026-09-05T14:00:00Z',
    logo: 'https://images.unsplash.com/photo-1532649538693-f3a2ec1bf8bd?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-violet-400 bg-violet-500/10 text-violet-300',
    website: 'https://nairobitti.ac.ke',
    county: 'Nairobi',
    generalContacts: {
      phone: '+254 20 676 0482',
      email: 'info@nairobitti.ac.ke',
      emergency: '+254 722 000 006',
      postalAddress: 'P.O. Box 30039 - 00100, Mogira Road, Parklands, Nairobi, Kenya',
    },
    campuses: [
      {
        id: 'ntti-main',
        institutionId: 'ntti',
        name: 'Main Campus (Mogira Road, Parklands)',
        county: 'Nairobi',
        town: 'Parklands / Ngara',
        address: 'Mogira Road, off Ring Road Ngara, Parklands, Nairobi',
        coordinates: { lat: -1.2681, lng: 36.8229 },
        contacts: { phone: '+254 20 676 0482', email: 'principal@nairobitti.ac.ke' },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'ntti-ict',
        institutionId: 'ntti',
        name: 'Department of Information Communication Technology',
        code: 'DICT-NTTI',
        departments: ['Computer Studies', 'Cybersecurity'],
      },
      {
        id: 'ntti-health',
        institutionId: 'ntti',
        name: 'Department of Health & Applied Sciences',
        code: 'DHAS-NTTI',
        departments: ['Pharmaceutical Technology', 'Food Technology'],
      },
    ],
    programmes: [
      {
        id: 'ntti-dict-knec',
        institutionId: 'ntti',
        code: 'NTTI-DICT-6',
        name: 'Diploma in Information Communication Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'ntti-ict',
        department: 'Computer Studies',
        durationYears: 3,
        tvetaAccredited: true,
      },
      {
        id: 'ntti-pharm-tech',
        institutionId: 'ntti',
        code: 'NTTI-PHARM-6',
        name: 'Diploma in Pharmaceutical Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'ntti-health',
        department: 'Pharmaceutical Technology',
        durationYears: 3,
        tvetaAccredited: true,
      },
    ],
  },

  // 7. THE ELDORET NATIONAL POLYTECHNIC (Eldoret)
  {
    id: 'eldoret-poly',
    name: 'The Eldoret National Polytechnic',
    shortName: 'TENP',
    type: 'National Polytechnic',
    ownership: 'Public',
    regulator: 'TVETA',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'TVETA/PUB/NP/0004/2017',
    accreditation: 'Accredited National Polytechnic by TVETA Kenya',
    source: 'TVET Authority Official Register & TENP Registry',
    lastVerifiedAt: '2026-09-05T15:00:00Z',
    logo: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-orange-400 bg-orange-500/10 text-orange-300',
    website: 'https://tenp.ac.ke',
    county: 'Uasin Gishu',
    generalContacts: {
      phone: '+254 53 206 3330',
      email: 'info@tenp.ac.ke',
      emergency: '+254 722 000 007',
      postalAddress: 'P.O. Box 4461 - 30100, Eldoret, Kenya',
    },
    campuses: [
      {
        id: 'eldoret-poly-main',
        institutionId: 'eldoret-poly',
        name: 'Main Campus (Eldoret-Kapsabet Road)',
        county: 'Uasin Gishu',
        town: 'Eldoret',
        address: 'Eldoret-Kapsabet Road, Eldoret',
        coordinates: { lat: 0.4952, lng: 35.2758 },
        contacts: { phone: '+254 53 206 3330', email: 'principal@tenp.ac.ke' },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'tenp-cs',
        institutionId: 'eldoret-poly',
        name: 'Department of Computing and Informatics',
        code: 'DCI',
        departments: ['Informatics & Data', 'Network Administration'],
      },
    ],
    programmes: [
      {
        id: 'tenp-dict',
        institutionId: 'eldoret-poly',
        code: 'TENP-DICT-6',
        name: 'Diploma in Information Communication Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'tenp-cs',
        department: 'Informatics & Data',
        durationYears: 3,
        tvetaAccredited: true,
      },
    ],
  },

  // 8. THE NYERI NATIONAL POLYTECHNIC (Nyeri)
  {
    id: 'nyeri-poly',
    name: 'The Nyeri National Polytechnic',
    shortName: 'Nyeri NP',
    type: 'National Polytechnic',
    ownership: 'Public',
    regulator: 'TVETA',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'TVETA/PUB/NP/0006/2017',
    accreditation: 'Accredited National Polytechnic by TVETA Kenya',
    source: 'TVET Authority Official Register',
    lastVerifiedAt: '2026-09-05T16:00:00Z',
    logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-rose-400 bg-rose-500/10 text-rose-300',
    website: 'https://thenyeripoly.ac.ke',
    county: 'Nyeri',
    generalContacts: {
      phone: '+254 61 203 2330',
      email: 'info@thenyeripoly.ac.ke',
      emergency: '+254 722 000 008',
      postalAddress: 'P.O. Box 465 - 10100, Nyeri, Kenya',
    },
    campuses: [
      {
        id: 'nyeri-poly-main',
        institutionId: 'nyeri-poly',
        name: 'Main Campus (Nyeri Town)',
        county: 'Nyeri',
        town: 'Nyeri',
        address: 'Near Nyeri Town Centre, Nyeri',
        coordinates: { lat: -0.4201, lng: 36.9475 },
        contacts: { phone: '+254 61 203 2330', email: 'principal@thenyeripoly.ac.ke' },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'nnp-ict',
        institutionId: 'nyeri-poly',
        name: 'Department of ICT and Information Studies',
        code: 'DICT',
        departments: ['Computing and Software Technology'],
      },
    ],
    programmes: [
      {
        id: 'nnp-dict',
        institutionId: 'nyeri-poly',
        code: 'NNP-DICT-6',
        name: 'Diploma in Information Communication Technology (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'KNEC',
        schoolId: 'nnp-ict',
        department: 'Computing and Software Technology',
        durationYears: 3,
        tvetaAccredited: true,
      },
    ],
  },

  // 9. KOITALEEL SAMOEI UNIVERSITY COLLEGE (Nandi - University College)
  {
    id: 'koitaleel-uc',
    name: 'Koitaleel Samoei University College',
    shortName: 'KSUC',
    type: 'University College',
    ownership: 'Public',
    regulator: 'CUE',
    licensingStatus: 'Constituent College',
    registrationNumber: 'CUE/PUB/UC/001/2018',
    accreditation: 'Constituent College of the University of Nairobi • CUE Approved',
    source: 'Commission for University Education (CUE) Official Register & KSUC Academic Registry',
    lastVerifiedAt: '2026-09-06T10:00:00Z',
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-yellow-400 bg-yellow-500/10 text-yellow-300',
    website: 'https://ksu.ac.ke',
    county: 'Nandi',
    generalContacts: {
      phone: '+254 740 183 955',
      email: 'info@ksu.ac.ke',
      emergency: '+254 740 183 956',
      postalAddress: 'P.O. Box 5 - 30307, Mosoriot, Nandi County, Kenya',
    },
    campuses: [
      {
        id: 'koitaleel-main',
        institutionId: 'koitaleel-uc',
        name: 'Mosoriot Main Campus',
        county: 'Nandi',
        town: 'Mosoriot',
        address: 'Eldoret-Kapsabet Highway, Mosoriot, Nandi',
        coordinates: { lat: 0.3155, lng: 35.1582 },
        contacts: { phone: '+254 740 183 955', email: 'principal@ksu.ac.ke' },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'ksuc-business',
        institutionId: 'koitaleel-uc',
        name: 'School of Business and Economics',
        code: 'SBE',
        departments: ['Department of Finance and Accounting', 'Department of Management Science'],
      },
      {
        id: 'ksuc-law',
        institutionId: 'koitaleel-uc',
        name: 'School of Law',
        code: 'SOL',
        departments: ['Department of Commercial Law', 'Department of Public Law'],
      },
    ],
    programmes: [
      {
        id: 'ksuc-bcom',
        institutionId: 'koitaleel-uc',
        code: 'KSUC-BCOM',
        name: 'Bachelor of Commerce',
        award: 'Bachelor',
        level: 'Bachelor Degree',
        examiningBody: 'University Senate',
        schoolId: 'ksuc-business',
        department: 'Department of Finance and Accounting',
        durationYears: 4,
        cueAccredited: true,
      },
      {
        id: 'ksuc-llb',
        institutionId: 'koitaleel-uc',
        code: 'KSUC-LLB',
        name: 'Bachelor of Laws (LL.B)',
        award: 'Bachelor',
        level: 'Bachelor Degree',
        examiningBody: 'University Senate',
        schoolId: 'ksuc-law',
        department: 'Department of Public Law',
        durationYears: 4,
        cueAccredited: true,
      },
    ],
  },

  // 10. KANGEMI VOCATIONAL TRAINING CENTRE (Nairobi - Vocational Training Centre)
  {
    id: 'kangemi-vtc',
    name: 'Kangemi Vocational Training Centre',
    shortName: 'Kangemi VTC',
    type: 'Vocational Training Centre',
    ownership: 'Public',
    regulator: 'TVETA',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'TVETA/PUB/VTC/0045/2018',
    accreditation: 'County Government of Nairobi & TVETA Registered Vocational Centre',
    source: 'TVET Authority Official Register & Nairobi City County TVET Directorate',
    lastVerifiedAt: '2026-09-06T11:00:00Z',
    logo: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-lime-400 bg-lime-500/10 text-lime-300',
    website: 'https://nairobi.go.ke/vocational-training',
    county: 'Nairobi',
    generalContacts: {
      phone: '+254 20 222 1414',
      email: 'kangemivtc@nairobi.go.ke',
      emergency: '+254 722 000 010',
      postalAddress: 'P.O. Box 30075 - 00100, Kangemi, Nairobi, Kenya',
    },
    campuses: [
      {
        id: 'kangemi-vtc-main',
        institutionId: 'kangemi-vtc',
        name: 'Kangemi Centre (Kangemi, Westlands)',
        county: 'Nairobi',
        town: 'Kangemi',
        address: 'Off Waiyaki Way, Kangemi Market Road, Nairobi',
        coordinates: { lat: -1.2618, lng: 36.7452 },
        contacts: { phone: '+254 20 222 1414', email: 'manager@kangemivtc.org' },
        isMainCampus: true,
      },
    ],
    schools: [
      {
        id: 'kvtc-it',
        institutionId: 'kangemi-vtc',
        name: 'Department of ICT and Digital Skills',
        code: 'DICT-VTC',
        departments: ['Digital Literacy & Computer Applications'],
      },
      {
        id: 'kvtc-technical',
        institutionId: 'kangemi-vtc',
        name: 'Department of Technical Trades',
        code: 'DTT',
        departments: ['Electrical Installation', 'Plumbing & Pipefitting'],
      },
    ],
    programmes: [
      {
        id: 'kvtc-artisan-ict',
        institutionId: 'kangemi-vtc',
        code: 'VTC-ART-ICT',
        name: 'Artisan Certificate in Information Communication Technology (Level 4)',
        award: 'Artisan',
        level: 'Artisan (Level 4)',
        examiningBody: 'NITA',
        schoolId: 'kvtc-it',
        department: 'Digital Literacy & Computer Applications',
        durationYears: 1,
        tvetaAccredited: true,
      },
      {
        id: 'kvtc-artisan-elec',
        institutionId: 'kangemi-vtc',
        code: 'VTC-ART-ELEC',
        name: 'Artisan in Electrical Installation (Level 4)',
        award: 'Artisan',
        level: 'Artisan (Level 4)',
        examiningBody: 'NITA',
        schoolId: 'kvtc-technical',
        department: 'Electrical Installation',
        durationYears: 1,
        tvetaAccredited: true,
      },
    ],
  },

  // 11. KENYA MEDICAL TRAINING COLLEGE (KMTC - Other Accredited Institution)
  {
    id: 'kmtc',
    name: 'Kenya Medical Training College',
    shortName: 'KMTC',
    type: 'Other Accredited Institution',
    ownership: 'Public',
    regulator: 'Other',
    licensingStatus: 'Registered and Licensed',
    registrationNumber: 'KMTC/MOH/ACT/1990',
    accreditation: 'State Corporation under Ministry of Health Kenya • 71 Campuses Nationwide',
    source: 'Ministry of Health Kenya & KMTC Academic Registry',
    lastVerifiedAt: '2026-09-06T12:00:00Z',
    logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=160&auto=format&fit=crop&q=80',
    badgeColor: 'border-red-400 bg-red-500/10 text-red-300',
    website: 'https://kmtc.ac.ke',
    county: 'Nairobi',
    generalContacts: {
      phone: '+254 20 272 5711',
      email: 'info@kmtc.ac.ke',
      emergency: '+254 20 272 5712',
      postalAddress: 'P.O. Box 30195 - 00100, Old Mbagathi Road, Nairobi, Kenya',
    },
    campuses: [
      {
        id: 'kmtc-nairobi-main',
        institutionId: 'kmtc',
        name: 'Nairobi Main Campus (KNH Grounds)',
        county: 'Nairobi',
        town: 'Upper Hill',
        address: 'Old Mbagathi Road, Adjacent to Kenyatta National Hospital, Nairobi',
        coordinates: { lat: -1.3021, lng: 36.8085 },
        contacts: { phone: '+254 20 272 5711', email: 'nairobicampus@kmtc.ac.ke' },
        isMainCampus: true,
      },
      {
        id: 'kmtc-mombasa',
        institutionId: 'kmtc',
        name: 'Mombasa Campus (CPGH Grounds)',
        county: 'Mombasa',
        town: 'Mombasa',
        address: 'Coast Provincial General Hospital Grounds, Kisauni Road, Mombasa',
        coordinates: { lat: -4.0489, lng: 39.6762 },
        contacts: { phone: '+254 41 231 4200', email: 'mombasacampus@kmtc.ac.ke' },
      },
      {
        id: 'kmtc-kisumu',
        institutionId: 'kmtc',
        name: 'Kisumu Campus (JOOTRH Grounds)',
        county: 'Kisumu',
        town: 'Kisumu',
        address: 'Jaramogi Oginga Odinga Teaching & Referral Hospital Grounds, Kisumu',
        coordinates: { lat: -0.0988, lng: 34.7672 },
        contacts: { phone: '+254 57 202 1200', email: 'kisumucampus@kmtc.ac.ke' },
      },
    ],
    schools: [
      {
        id: 'kmtc-clinical-med',
        institutionId: 'kmtc',
        name: 'Department of Clinical Medicine',
        code: 'DCM',
        departments: ['Clinical Medicine & Surgery', 'Emergency Medicine'],
      },
      {
        id: 'kmtc-nursing',
        institutionId: 'kmtc',
        name: 'Department of Nursing Sciences',
        code: 'DNS',
        departments: ['Community Health Nursing', 'Critical Care Nursing'],
      },
      {
        id: 'kmtc-pharmacy',
        institutionId: 'kmtc',
        name: 'Department of Pharmacy',
        code: 'DP',
        departments: ['Clinical Pharmacy & Pharmacology'],
      },
    ],
    programmes: [
      {
        id: 'kmtc-dip-clinmed',
        institutionId: 'kmtc',
        code: 'KMTC-DCM-6',
        name: 'Diploma in Clinical Medicine and Surgery (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'Other',
        schoolId: 'kmtc-clinical-med',
        department: 'Clinical Medicine & Surgery',
        durationYears: 3,
      },
      {
        id: 'kmtc-dip-krchn',
        institutionId: 'kmtc',
        code: 'KMTC-KRCHN-6',
        name: 'Diploma in Kenya Registered Community Health Nursing (KRCHN) (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'Other',
        schoolId: 'kmtc-nursing',
        department: 'Community Health Nursing',
        durationYears: 3,
      },
      {
        id: 'kmtc-dip-pharm',
        institutionId: 'kmtc',
        code: 'KMTC-PHARM-6',
        name: 'Diploma in Pharmacy (Level 6)',
        award: 'Diploma',
        level: 'Diploma (Level 6)',
        examiningBody: 'Other',
        schoolId: 'kmtc-pharmacy',
        department: 'Clinical Pharmacy & Pharmacology',
        durationYears: 3,
      },
    ],
  },
];

// =========================================================================
// REAL VERIFIED FACILITIES FOR TVET & POLYTECHNIC INSTITUTIONS
// =========================================================================

export const TVETA_FACILITIES: CampusFacility[] = [
  // Thika Technical Training Institute
  {
    id: 'fac-ttti-ict-centre',
    institutionId: 'thika-tti',
    campusId: 'ttti-main',
    name: 'TTTI ICT Centre & Digital Software Lab',
    category: 'TECHNOLOGY',
    building: 'Engineering & Computing Complex',
    floor: '1st Floor',
    room: 'Lab 101 - 104',
    description: 'Equipped with 180 modern computers, high-speed NOFBI fiber internet, Linux & Windows environments, Cisco networking racks, and TVET-CDACC digital assessment stations.',
    openingHours: 'Mon - Fri: 07:30 - 20:00 | Sat: 08:00 - 16:00',
    contact: '+254 67 222 1952',
    email: 'ict@thikatechnical.ac.ke',
    location: 'Main Campus, next to Administration Block',
    coordinates: { lat: -1.0378, lng: 37.0765 },
    availableServices: ['TVET-CDACC Online Assessment', 'KNEC Registration Portal', 'Fibre Wi-Fi Access', 'Programming Workstations'],
    isAccessible: true,
  },
  {
    id: 'fac-ttti-library',
    institutionId: 'thika-tti',
    campusId: 'ttti-main',
    name: 'Technical Resource Library & E-Learning Centre',
    category: 'ACADEMIC',
    building: 'Library Block',
    floor: 'Ground & 1st Floor',
    description: 'Specialized collection of TVET engineering manuals, KNEC past assessment papers, digital textbooks, and quiet study stations.',
    openingHours: 'Mon - Fri: 08:00 - 20:00 | Sat: 08:30 - 15:00',
    contact: '+254 67 222 1952',
    location: 'Opposite Mechanical Workshops',
    coordinates: { lat: -1.0375, lng: 37.0768 },
    availableServices: ['KNEC Past Paper Bank', 'E-Granthagar TVET Repository', 'Book Lending', 'Discussion Cubicles'],
    isAccessible: true,
  },
  {
    id: 'fac-ttti-mech-workshop',
    institutionId: 'thika-tti',
    campusId: 'ttti-main',
    name: 'Mechanical & Automotive Training Workshops',
    category: 'ACADEMIC',
    building: 'Mechanical Engineering Complex',
    floor: 'Ground Floor',
    room: 'Heavy Machinery & Lathe Bay',
    description: 'Modern automotive engine diagnosis bays, CNC lathes, hydraulic presses, wheel balancing rigs, and metal fabrication workshops.',
    openingHours: 'Mon - Fri: 08:00 - 17:00',
    contact: '+254 67 222 1952',
    location: 'Lower Campus Workshop Area',
    coordinates: { lat: -1.0382, lng: 37.0762 },
    availableServices: ['Engine Diagnostics', 'CNC Machining', 'Welding & Fabrication', 'Plumbing Practicals'],
    isAccessible: true,
  },
  {
    id: 'fac-ttti-clinic',
    institutionId: 'thika-tti',
    campusId: 'ttti-main',
    name: 'Student Health & Wellness Dispensary',
    category: 'HEALTH',
    building: 'Student Welfare Block',
    floor: 'Ground Floor',
    description: 'First aid, clinical consultations, emergency care, and general health support for enrolled students.',
    openingHours: 'Mon - Fri: 08:00 - 18:00 (Emergency calls 24/7)',
    contact: '+254 67 222 1952',
    location: 'Next to Main Gate Dispensary Wing',
    coordinates: { lat: -1.0379, lng: 37.0766 },
    availableServices: ['First Aid Treatment', 'Counseling Services', 'Referral to Thika Level 5 Hospital'],
    isAccessible: true,
  },

  // The Kabete National Polytechnic
  {
    id: 'fac-kabete-mecha-hub',
    institutionId: 'kabete-poly',
    campusId: 'kabete-main',
    name: 'National Mechatronics & Robotics Centre',
    category: 'TECHNOLOGY',
    building: 'Mechatronics Building',
    floor: 'Ground Floor',
    description: 'State-of-the-art automation laboratory equipped with FESTO pneumatic trainers, industrial PLC panels, robotic arms, and SCADA monitoring systems.',
    openingHours: 'Mon - Sat: 08:00 - 19:00',
    contact: '+254 20 205 9931',
    location: 'Waiyaki Way Campus Quadrangle',
    coordinates: { lat: -1.2592, lng: 36.7215 },
    availableServices: ['PLC Programming', 'FESTO Pneumatics', 'Robotics Simulation', 'Industrial Automation Certifications'],
    isAccessible: true,
  },
  {
    id: 'fac-kabete-ict-lab',
    institutionId: 'kabete-poly',
    campusId: 'kabete-main',
    name: 'Kabete Cisco Networking & Computing Academy',
    category: 'TECHNOLOGY',
    building: 'Main ICT Building',
    floor: '2nd Floor',
    description: 'High-speed networking lab with Cisco Catalyst switches, routers, cybersecurity test-bed, and 200 student workstations.',
    openingHours: 'Mon - Fri: 07:30 - 20:00 | Sat: 08:00 - 16:00',
    contact: '+254 20 205 9931',
    location: 'Near Administration Tower',
    coordinates: { lat: -1.2590, lng: 36.7218 },
    availableServices: ['Cisco CCNA Certification', 'Cybersecurity Training', 'Wi-Fi Hub', 'Software Lab'],
    isAccessible: true,
  },

  // Kisumu National Polytechnic
  {
    id: 'fac-knp-innovation-hub',
    institutionId: 'kisumu-poly',
    campusId: 'kisumu-poly-main',
    name: 'Lake Region TVET Innovation & Incubation Centre',
    category: 'TECHNOLOGY',
    building: 'Science & Technology Complex',
    floor: '1st Floor',
    description: 'Student entrepreneurship hub providing high-speed internet, 3D printers, IoT hardware kits, and incubation mentoring.',
    openingHours: 'Mon - Fri: 08:00 - 19:00',
    contact: '+254 57 202 2071',
    location: 'Technology Road, Main Campus',
    coordinates: { lat: -0.1022, lng: 34.7617 },
    availableServices: ['3D Printing Prototyping', 'IoT Sensor Development', 'Tech Incubation Desk'],
    isAccessible: true,
  },

  // Kenya Coast National Polytechnic
  {
    id: 'fac-kcnp-marine-sim',
    institutionId: 'kenya-coast-poly',
    campusId: 'kcnp-main',
    name: 'Maritime Navigation & Marine Simulator Complex',
    category: 'ACADEMIC',
    building: 'Maritime Training Centre',
    floor: 'Ground & 1st Floor',
    description: 'Certified bridge navigation simulator, marine radar systems, ship propulsion training cutaways, and coastal port logistics training consoles.',
    openingHours: 'Mon - Fri: 08:00 - 17:00',
    contact: '+254 41 249 2222',
    location: 'Kisauni Road Campus, Maritime Wing',
    coordinates: { lat: -4.0532, lng: 39.6738 },
    availableServices: ['Ship Navigation Simulator', 'Port Logistics Software', 'Radar Operation Certification'],
    isAccessible: true,
  },

  // KMTC Nairobi
  {
    id: 'fac-kmtc-skills-lab',
    institutionId: 'kmtc',
    campusId: 'kmtc-nairobi-main',
    name: 'Clinical Skills & High-Fidelity Simulation Lab',
    category: 'ACADEMIC',
    building: 'Clinical Training Wing',
    floor: '2nd Floor',
    description: 'Clinical simulation ward with high-fidelity mannequins, surgical scrub bay, delivery suites, and emergency resuscitation stations.',
    openingHours: 'Mon - Fri: 07:30 - 18:00 | Sat: 08:30 - 14:00',
    contact: '+254 20 272 5711',
    location: 'KNH Complex, KMTC Nairobi',
    coordinates: { lat: -1.3021, lng: 36.8085 },
    availableServices: ['Surgical Skills Practice', 'CPR & Resuscitation', 'Clinical Assessments'],
    isAccessible: true,
  },
];

// =========================================================================
// REAL VERIFIED UNITS FOR TVET & POLYTECHNIC PROGRAMMES
// =========================================================================

export const TVETA_PROGRAMME_UNITS: ProgrammeUnit[] = [
  // Thika Technical Training Institute - DICT KNEC (Year 1, Term 1 / Module 1)
  {
    id: 'unit-ttti-dict-101',
    institutionId: 'thika-tti',
    programmeId: 'ttti-dict-knec',
    code: 'DICT 101',
    title: 'Introduction to ICT & Computer Applications',
    year: 1,
    semester: 'Term 1',
    credits: 3,
    description: 'Foundations of computer systems, architecture, operating system configuration, and productivity tools.',
    lecturerName: 'Eng. Peter Mwangi',
    lecturerEmail: 'pmwangi@thikatechnical.ac.ke',
    isCore: true,
  },
  {
    id: 'unit-ttti-dict-102',
    institutionId: 'thika-tti',
    programmeId: 'ttti-dict-knec',
    code: 'DICT 102',
    title: 'Structured Programming (C / Python)',
    year: 1,
    semester: 'Term 1',
    credits: 4,
    description: 'Algorithm design, flowcharts, pseudocode, procedural control structures, arrays, and file handling.',
    lecturerName: 'Ms. Faith Njeri',
    lecturerEmail: 'fnjeri@thikatechnical.ac.ke',
    isCore: true,
  },
  {
    id: 'unit-ttti-dict-103',
    institutionId: 'thika-tti',
    programmeId: 'ttti-dict-knec',
    code: 'DICT 103',
    title: 'Operating Systems & System Software',
    year: 1,
    semester: 'Term 2',
    credits: 3,
    description: 'Process management, memory management, file systems, Linux command-line, and virtualization.',
    lecturerName: 'Mr. David Kariuki',
    lecturerEmail: 'dkariuki@thikatechnical.ac.ke',
    isCore: true,
  },
  {
    id: 'unit-ttti-dict-104',
    institutionId: 'thika-tti',
    programmeId: 'ttti-dict-knec',
    code: 'DICT 104',
    title: 'Database Management Systems (SQL & Relational Design)',
    year: 1,
    semester: 'Term 2',
    credits: 4,
    description: 'Entity-relationship modeling, relational algebra, SQL DDL/DML, normalization, and indexing.',
    lecturerName: 'Eng. Peter Mwangi',
    lecturerEmail: 'pmwangi@thikatechnical.ac.ke',
    isCore: true,
  },
  {
    id: 'unit-ttti-dict-201',
    institutionId: 'thika-tti',
    programmeId: 'ttti-dict-knec',
    code: 'DICT 201',
    title: 'Data Communication & Computer Networks',
    year: 2,
    semester: 'Term 1',
    credits: 4,
    description: 'OSI 7-layer and TCP/IP models, subnetting, switching, router configurations, and wireless network security.',
    lecturerName: 'Eng. John Kamau',
    lecturerEmail: 'jkamau@thikatechnical.ac.ke',
    isCore: true,
  },
  {
    id: 'unit-ttti-dict-202',
    institutionId: 'thika-tti',
    programmeId: 'ttti-dict-knec',
    code: 'DICT 202',
    title: 'Object-Oriented Programming (Java / C#)',
    year: 2,
    semester: 'Term 1',
    credits: 4,
    description: 'Classes, encapsulation, inheritance, polymorphism, design patterns, and GUI applications.',
    lecturerName: 'Ms. Faith Njeri',
    lecturerEmail: 'fnjeri@thikatechnical.ac.ke',
    isCore: true,
  },

  // Kabete National Polytechnic - Mechatronics (Year 1, Term 1)
  {
    id: 'unit-kabete-mecha-101',
    institutionId: 'kabete-poly',
    programmeId: 'kabete-mecha-l6',
    code: 'MECH 101',
    title: 'Industrial Pneumatics & Electro-Pneumatics',
    year: 1,
    semester: 'Term 1',
    credits: 4,
    description: 'Compressed air generation, pneumatic actuators, directional valves, electrical control circuits, and ladder diagrams.',
    lecturerName: 'Eng. Patrick Omondi',
    isCore: true,
  },
  {
    id: 'unit-kabete-mecha-102',
    institutionId: 'kabete-poly',
    programmeId: 'kabete-mecha-l6',
    code: 'MECH 102',
    title: 'Programmable Logic Controllers (PLC Programming)',
    year: 1,
    semester: 'Term 1',
    credits: 4,
    description: 'PLC architecture, ladder logic, structured text, timers, counters, sensors, and actuator interfacing.',
    lecturerName: 'Eng. Patrick Omondi',
    isCore: true,
  },

  // Kisumu National Polytechnic - Civil Engineering
  {
    id: 'unit-knp-civil-101',
    institutionId: 'kisumu-poly',
    programmeId: 'knp-civil-diploma',
    code: 'CIV 101',
    title: 'Engineering Surveying & Leveling I',
    year: 1,
    semester: 'Term 1',
    credits: 4,
    description: 'Chain surveying, optical leveling, theodolite traverse, contouring, and total station fieldwork.',
    lecturerName: 'Surv. George Otieno',
    isCore: true,
  },
  {
    id: 'unit-knp-civil-102',
    institutionId: 'kisumu-poly',
    programmeId: 'knp-civil-diploma',
    code: 'CIV 102',
    title: 'Strength of Materials & Structural Analysis',
    year: 1,
    semester: 'Term 1',
    credits: 4,
    description: 'Stress, strain, Hooke law, bending moments, shearing forces, and deflection in beams.',
    lecturerName: 'Eng. Mercy Achieng',
    isCore: true,
  },

  // KMTC Nairobi - Diploma in Clinical Medicine
  {
    id: 'unit-kmtc-cm-101',
    institutionId: 'kmtc',
    programmeId: 'kmtc-dip-clinmed',
    code: 'MED 101',
    title: 'Human Anatomy & Physiology',
    year: 1,
    semester: 'Semester 1',
    credits: 5,
    description: 'Gross anatomy, histological organ systems, cardiovascular, respiratory, nervous, and endocrine mechanics.',
    lecturerName: 'Dr. Julius Mutua',
    isCore: true,
  },
  {
    id: 'unit-kmtc-cm-102',
    institutionId: 'kmtc',
    programmeId: 'kmtc-dip-clinmed',
    code: 'MED 102',
    title: 'Clinical Pharmacology & Therapeutics',
    year: 1,
    semester: 'Semester 1',
    credits: 4,
    description: 'Pharmacokinetics, pharmacodynamics, drug dosage calculations, adverse reactions, and antimicrobial therapy.',
    lecturerName: 'Pharm. Susan Chebet',
    isCore: true,
  },
];
